//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IPPEA.EntityData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Admin
    {
        public int uid { get; set; }
        public string PrimaryEmail { get; set; }
        public string SecondaryEmail { get; set; }
        public string EMailMethod { get; set; }
        public string EMailServer { get; set; }
        public string SSLPath { get; set; }
        public string TransMethod { get; set; }
        public string StoreName { get; set; }
        public Nullable<int> AddressID { get; set; }
        public Nullable<short> ShipType { get; set; }
        public Nullable<short> ShipType2 { get; set; }
        public Nullable<short> PrmShipIsActive { get; set; }
        public Nullable<short> HandlingIsActive { get; set; }
        public string DeletePolicy { get; set; }
        public Nullable<short> DeleteSchedule { get; set; }
        public string ISOCurrency { get; set; }
        public string LCID { get; set; }
        public string ShipMin { get; set; }
        public string CODAmount { get; set; }
        public string SpcShipAmt { get; set; }
        public string OandaID { get; set; }
        public Nullable<short> ActivateOanda { get; set; }
        public string LivePersonID { get; set; }
        public Nullable<short> LivePersonActive { get; set; }
        public string SFID { get; set; }
        public string PhysPath { get; set; }
        public Nullable<short> BackOrderBilling { get; set; }
        public Nullable<int> TopMenuBarNav { get; set; }
        public Nullable<int> FooterNav { get; set; }
        public Nullable<int> LeftNav { get; set; }
        public Nullable<int> RightNav { get; set; }
        public Nullable<int> AllowMultipleCoupons { get; set; }
        public Nullable<int> AllowCouponWithDiscount { get; set; }
        public Nullable<int> TaxShipping { get; set; }
        public Nullable<int> TaxHandling { get; set; }
        public string AdditionalAddressHandling { get; set; }
        public Nullable<int> AllOrderHandling { get; set; }
        public string HandlingAmount { get; set; }
        public Nullable<int> AddProductStyle { get; set; }
        public string SiteURL { get; set; }
        public string MetaTag { get; set; }
        public string MetaDescription { get; set; }
        public Nullable<decimal> NextOrderNumber { get; set; }
        public Nullable<int> DatabaseType { get; set; }
        public Nullable<int> CCOnline { get; set; }
        public Nullable<int> ECheckOnline { get; set; }
        public Nullable<int> CVVIsActive { get; set; }
        public string ProductSort { get; set; }
        public string PremShipLabel { get; set; }
        public Nullable<int> AcceptCC { get; set; }
        public string MMPassword { get; set; }
        public string MMUserName { get; set; }
        public string SiteKeywords { get; set; }
        public string SiteDescription { get; set; }
        public string sfLogin { get; set; }
        public string sfPassword { get; set; }
        public Nullable<int> AllowMultiShip { get; set; }
        public string WebLicense { get; set; }
        public string SearchOnFields { get; set; }
        public string AdminGuid { get; set; }
        public string EncryptionPublicKey { get; set; }
        public Nullable<bool> ConvertedFrom3DES { get; set; }
    }
}
