//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IPPEA.EntityData
{
    using System;
    using System.Collections.Generic;
    
    public partial class AspNetUser
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AspNetUser()
        {
            this.AspNetCustomers = new HashSet<AspNetCustomer>();
            this.AspNetEmployees = new HashSet<AspNetEmployee>();
            this.AspNetManufacturers = new HashSet<AspNetManufacturer>();
            this.AspNetUserActivityLogs = new HashSet<AspNetUserActivityLog>();
            this.AspNetUserClaims = new HashSet<AspNetUserClaim>();
            this.AspNetUserLogins = new HashSet<AspNetUserLogin>();
            this.AspNetUserPermissions = new HashSet<AspNetUserPermission>();
            this.AspNetVendors = new HashSet<AspNetVendor>();
            this.IPPEA_DATA_ConversationMessage = new HashSet<IPPEA_DATA_ConversationMessage>();
            this.IPPEA_DATA_ConversationUserMentions = new HashSet<IPPEA_DATA_ConversationUserMentions>();
            this.IPPEA_DATA_ProductPriceUpdate = new HashSet<IPPEA_DATA_ProductPriceUpdate>();
            this.IPPEA_DATA_QandAAnswer = new HashSet<IPPEA_DATA_QandAAnswer>();
            this.IPPEA_DATA_SalesTaxExemption = new HashSet<IPPEA_DATA_SalesTaxExemption>();
            this.IPPEA_DATA_SalesTaxExemption1 = new HashSet<IPPEA_DATA_SalesTaxExemption>();
            this.IPPEA_DATA_SalesTaxExemption2 = new HashSet<IPPEA_DATA_SalesTaxExemption>();
            this.IPPEA_DATA_VendorPriceUpdate = new HashSet<IPPEA_DATA_VendorPriceUpdate>();
            this.AspNetRoles = new HashSet<AspNetRole>();
        }
    
        public string Id { get; set; }
        public string Email { get; set; }
        public bool EmailConfirmed { get; set; }
        public string PasswordHash { get; set; }
        public string SecurityStamp { get; set; }
        public string PhoneNumber { get; set; }
        public bool PhoneNumberConfirmed { get; set; }
        public bool TwoFactorEnabled { get; set; }
        public Nullable<System.DateTime> LockoutEndDateUtc { get; set; }
        public bool LockoutEnabled { get; set; }
        public int AccessFailedCount { get; set; }
        public string UserName { get; set; }
        public System.DateTime CreateDateUtc { get; set; }
        public Nullable<System.DateTime> MigrateDateUtc { get; set; }
        public Nullable<System.DateTime> LastLoginDateUtc { get; set; }
        public Nullable<System.DateTime> LastLogoutDateUtc { get; set; }
        public Nullable<System.DateTime> LastLoginAccessFailedDateUtc { get; set; }
        public Nullable<System.DateTime> LastEmailChangeDateUtc { get; set; }
        public Nullable<System.DateTime> LastForgotPasswordRequestDateUtc { get; set; }
        public Nullable<System.DateTime> LastPasswordChangeDateUtc { get; set; }
        public bool RequiresEmailConfirmation { get; set; }
        public string DisplayName { get; set; }
        public Nullable<System.DateTime> EmailConfirmedDateUtc { get; set; }
        public Nullable<System.DateTime> LastActivityUtc { get; set; }
        public Nullable<System.DateTimeOffset> PasswordResetRequiredDateUtc { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AspNetCustomer> AspNetCustomers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AspNetEmployee> AspNetEmployees { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AspNetManufacturer> AspNetManufacturers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AspNetUserActivityLog> AspNetUserActivityLogs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AspNetUserClaim> AspNetUserClaims { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AspNetUserLogin> AspNetUserLogins { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AspNetUserPermission> AspNetUserPermissions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AspNetVendor> AspNetVendors { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IPPEA_DATA_ConversationMessage> IPPEA_DATA_ConversationMessage { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IPPEA_DATA_ConversationUserMentions> IPPEA_DATA_ConversationUserMentions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IPPEA_DATA_ProductPriceUpdate> IPPEA_DATA_ProductPriceUpdate { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IPPEA_DATA_QandAAnswer> IPPEA_DATA_QandAAnswer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IPPEA_DATA_SalesTaxExemption> IPPEA_DATA_SalesTaxExemption { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IPPEA_DATA_SalesTaxExemption> IPPEA_DATA_SalesTaxExemption1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IPPEA_DATA_SalesTaxExemption> IPPEA_DATA_SalesTaxExemption2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IPPEA_DATA_VendorPriceUpdate> IPPEA_DATA_VendorPriceUpdate { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AspNetRole> AspNetRoles { get; set; }
    }
}
