//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IPPEA.EntityData
{
    using System;
    using System.Collections.Generic;
    
    public partial class AspNet_SqlCacheTablesForChangeNotification
    {
        public string tableName { get; set; }
        public System.DateTime notificationCreated { get; set; }
        public int changeId { get; set; }
    }
}
