//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IPPEA.EntityData
{
    using System;
    using System.Collections.Generic;
    
    public partial class AttributeDetail
    {
        public int uid { get; set; }
        public Nullable<int> AttributeID { get; set; }
        public string Name { get; set; }
        public string Price { get; set; }
        public string Weight { get; set; }
        public Nullable<byte> PriceType { get; set; }
        public Nullable<byte> WeightType { get; set; }
        public Nullable<int> AttributeOrder { get; set; }
        public string SmallImage { get; set; }
        public string LargeImage { get; set; }
        public string FileLocation { get; set; }
    }
}
