//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IPPEA.EntityData
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerSpecificPricing
    {
        public int uid { get; set; }
        public Nullable<int> ProductID { get; set; }
        public Nullable<int> GroupID { get; set; }
    }
}
