//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IPPEA.EntityData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public int uid { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Pass { get; set; }
        public string EMail { get; set; }
        public Nullable<int> Subscribed { get; set; }
        public Nullable<int> CustGroupID { get; set; }
        public Nullable<int> Referrer { get; set; }
        public string HttpReferrer { get; set; }
        public string ReferrerDate { get; set; }
    }
}
