//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IPPEA.EntityData
{
    using System;
    using System.Collections.Generic;
    
    public partial class InventoryInfo
    {
        public int uid { get; set; }
        public Nullable<int> ProdID { get; set; }
        public Nullable<int> OnOrder { get; set; }
        public Nullable<int> Tracked { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<int> Notify { get; set; }
        public Nullable<int> InStock { get; set; }
        public Nullable<int> LowFlag { get; set; }
        public Nullable<int> CanBackOrder { get; set; }
        public Nullable<int> DefaultQTY { get; set; }
    }
}
