//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IPPEA.EntityData
{
    using System;
    using System.Collections.Generic;
    
    public partial class IP_DATA_HowToPageComments_Archive
    {
        public int ArchiveID { get; set; }
        public string ArchiveType { get; set; }
        public string ArchiveReason { get; set; }
        public int ArchiveUserID { get; set; }
        public System.DateTimeOffset ArchiveDt { get; set; }
        public int ID { get; set; }
        public string UserName { get; set; }
        public string EmailAddress { get; set; }
        public string Comment { get; set; }
        public int Approved { get; set; }
        public System.DateTime DateCreated { get; set; }
        public int HowToPageID { get; set; }
        public string OriginalUserName { get; set; }
        public string OriginalComment { get; set; }
        public Nullable<int> EmployeeId { get; set; }
        public Nullable<int> CustomerId { get; set; }
        public string IPAddress { get; set; }
        public string UserAgent { get; set; }
        public Nullable<int> ParentId { get; set; }
        public Nullable<System.DateTimeOffset> LockDate { get; set; }
        public Nullable<int> LockEmployeeId { get; set; }
    
        public virtual IPPEA_DATA_Employees IPPEA_DATA_Employees { get; set; }
    }
}
