//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IPPEA.EntityData
{
    using System;
    using System.Collections.Generic;
    
    public partial class IP_DATA_UserNickNames
    {
        public int ID { get; set; }
        public Nullable<int> UserID { get; set; }
        public string NickName { get; set; }
        public string Code { get; set; }
        public int CustomerNumber { get; set; }
    
        public virtual IPPEA_DATA_Customer IPPEA_DATA_Customer { get; set; }
    }
}
