//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IPPEA.EntityData
{
    using System;
    using System.Collections.Generic;
    
    public partial class IPPEA_DATA_VendorProducts
    {
        public int ID { get; set; }
        public int ProductID { get; set; }
        public int VendorID { get; set; }
        public string ManufacturerCode { get; set; }
        public decimal UnitPrice { get; set; }
        public Nullable<decimal> OriginalPrice { get; set; }
        public System.DateTime ValidFrom { get; set; }
        public System.DateTime ValidTo { get; set; }
    
        public virtual IPPEA_DATA_Product IPPEA_DATA_Product { get; set; }
        public virtual IPPEA_DATA_Vendor IPPEA_DATA_Vendor { get; set; }
    }
}
