//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IPPEA.EntityData
{
    using System;
    using System.Collections.Generic;
    
    public partial class IPPEA_DATA_VendorProductCategories
    {
        public int ID { get; set; }
        public Nullable<int> VendorID { get; set; }
        public Nullable<int> ManufacturerID { get; set; }
        public Nullable<int> ProductCategoryID { get; set; }
        public Nullable<decimal> Discount { get; set; }
        public string SubCategories { get; set; }
        public Nullable<bool> ExcludeOnFreightQuote { get; set; }
    }
}
