//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IPPEA.EntityData
{
    using System;
    using System.Collections.Generic;
    
    public partial class IPPEA_DATA_SalesTaxExemption_Archive
    {
        public int ArchiveID { get; set; }
        public string ArchiveType { get; set; }
        public string ArchiveReason { get; set; }
        public int ArchiveUserID { get; set; }
        public System.DateTimeOffset ArchiveDt { get; set; }
        public int Id { get; set; }
        public int CustomerId { get; set; }
        public int ExemptionTypeId { get; set; }
        public string CountryCode { get; set; }
        public string StateProvinceCode { get; set; }
        public string CertificateNumber { get; set; }
        public System.DateTime ExpirationDate { get; set; }
        public int MediaId { get; set; }
        public int MediaResourceTypeId { get; set; }
        public Nullable<int> ReviewResultId { get; set; }
        public Nullable<System.DateTimeOffset> ReviewDate { get; set; }
        public string ReviewUserId { get; set; }
        public string ReviewComments { get; set; }
        public Nullable<System.DateTimeOffset> RevokeDate { get; set; }
        public string RevokeUserId { get; set; }
        public string RevokeComments { get; set; }
        public System.DateTimeOffset InsertDate { get; set; }
        public string InsertUserId { get; set; }
        public string IPAddress { get; set; }
        public string UserAgent { get; set; }
    
        public virtual IPPEA_DATA_Employees IPPEA_DATA_Employees { get; set; }
    }
}
