//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IPPEA.EntityData
{
    using System;
    using System.Collections.Generic;
    
    public partial class IPPEA_DATA_DoItYourselfStory
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public IPPEA_DATA_DoItYourselfStory()
        {
            this.IPPEA_DATA_DoItYourselfStoryProducts = new HashSet<IPPEA_DATA_DoItYourselfStoryProducts>();
            this.IPPEA_DATA_DoItYourselfStoryRatings = new HashSet<IPPEA_DATA_DoItYourselfStoryRatings>();
            this.IPPEA_DATA_DoItYourselfTools = new HashSet<IPPEA_DATA_DoItYourselfTools>();
        }
    
        public int Id { get; set; }
        public int CustomerId { get; set; }
        public string Problem { get; set; }
        public string OriginalProblem { get; set; }
        public string Solution { get; set; }
        public string OriginalSolution { get; set; }
        public int OriginalProductId { get; set; }
        public int StoryStatus { get; set; }
        public string ToolsOther { get; set; }
        public int ProjectLengthId { get; set; }
        public int DifficultyId { get; set; }
        public System.DateTimeOffset InsertDate { get; set; }
        public string IPAddress { get; set; }
        public string UserAgent { get; set; }
        public Nullable<int> EmployeeId { get; set; }
        public Nullable<System.DateTimeOffset> EmailSentDate { get; set; }
    
        public virtual IPPEA_DATA_Customer IPPEA_DATA_Customer { get; set; }
        public virtual IPPEA_DECODE_HowToDifficulty IPPEA_DECODE_HowToDifficulty { get; set; }
        public virtual IPPEA_DATA_Employees IPPEA_DATA_Employees { get; set; }
        public virtual IPPEA_DATA_Product IPPEA_DATA_Product { get; set; }
        public virtual IPPEA_DECODE_DiyProjectLength IPPEA_DECODE_DiyProjectLength { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IPPEA_DATA_DoItYourselfStoryProducts> IPPEA_DATA_DoItYourselfStoryProducts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IPPEA_DATA_DoItYourselfStoryRatings> IPPEA_DATA_DoItYourselfStoryRatings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IPPEA_DATA_DoItYourselfTools> IPPEA_DATA_DoItYourselfTools { get; set; }
    }
}
