//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IPPEA.EntityData
{
    using System;
    using System.Collections.Generic;
    
    public partial class IPPEA_DATA_AuthNetTransLog
    {
        public int ID { get; set; }
        public Nullable<System.DateTime> TranDate { get; set; }
        public string UserID { get; set; }
        public Nullable<int> TranTypeID { get; set; }
        public Nullable<int> ResponseCode { get; set; }
        public Nullable<int> ResponseReasonCode { get; set; }
        public string ResponseReasonText { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public byte[] CCNumber { get; set; }
        public string CCExpDate { get; set; }
        public int CustomerID { get; set; }
        public string ApprovalCode { get; set; }
        public string TransactionID { get; set; }
        public Nullable<int> BillingTypeID { get; set; }
        public string BAAccountName { get; set; }
        public string BABankName { get; set; }
        public byte[] BARoutingNumber { get; set; }
        public byte[] BAAccountNumber { get; set; }
    
        public virtual IPPEA_DATA_Customer IPPEA_DATA_Customer { get; set; }
    }
}
