//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IPPEA.EntityData
{
    using System;
    using System.Collections.Generic;
    
    public partial class IPPEA_DATA_OrderGroup
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public IPPEA_DATA_OrderGroup()
        {
            this.IPPEA_DATA_Checkout = new HashSet<IPPEA_DATA_Checkout>();
            this.IPPEA_DATA_ConversationOrderGroup = new HashSet<IPPEA_DATA_ConversationOrderGroup>();
            this.IPPEA_DATA_EmailLog = new HashSet<IPPEA_DATA_EmailLog>();
            this.IPPEA_DATA_EmailQueue = new HashSet<IPPEA_DATA_EmailQueue>();
            this.IPPEA_DATA_FreightQuoteRequest = new HashSet<IPPEA_DATA_FreightQuoteRequest>();
            this.IPPEA_DATA_OrderCoupons = new HashSet<IPPEA_DATA_OrderCoupons>();
            this.IPPEA_DATA_OrderCustomerReviewStatus = new HashSet<IPPEA_DATA_OrderCustomerReviewStatus>();
            this.IPPEA_DATA_OrderFormHeader = new HashSet<IPPEA_DATA_OrderFormHeader>();
            this.IPPEA_DATA_ProductBlogMentions = new HashSet<IPPEA_DATA_ProductBlogMentions>();
            this.IPPEA_DATA_ProductSocialMediaSubmission = new HashSet<IPPEA_DATA_ProductSocialMediaSubmission>();
            this.IPPEA_DATA_PTAuthorizations = new HashSet<IPPEA_DATA_PTAuthorizations>();
            this.IPPEA_DATA_Quotes = new HashSet<IPPEA_DATA_Quotes>();
        }
    
        public int ID { get; set; }
        public int CustomerID { get; set; }
        public Nullable<int> OrderStatusID { get; set; }
        public System.DateTime DateOrdered { get; set; }
        public string UserID { get; set; }
        public Nullable<bool> ShipTogether { get; set; }
        public Nullable<System.DateTime> ProcessDate { get; set; }
        public Nullable<decimal> AuthAmount { get; set; }
        public string AuthTransID { get; set; }
        public Nullable<bool> AuthCaptured { get; set; }
        public Nullable<bool> SendEmail { get; set; }
        public Nullable<bool> OrderPlaced { get; set; }
        public Nullable<bool> OrderSaved { get; set; }
        public Nullable<int> AffiliateID { get; set; }
        public string BMLAuthRequestID { get; set; }
        public string BMLAuthRequestToken { get; set; }
        public Nullable<decimal> BMLAuthAmount { get; set; }
        public Nullable<int> BMLPromoType { get; set; }
        public Nullable<int> OrderType { get; set; }
        public Nullable<bool> IsRedo { get; set; }
        public Nullable<int> RedoOriginalOrderFormID { get; set; }
        public Nullable<bool> HasRedo { get; set; }
        public Nullable<int> HasRedoOrderFormID { get; set; }
        public Nullable<decimal> OriginalBillTotal { get; set; }
        public Nullable<bool> TruckReminderEmailSent { get; set; }
        public string TemplateTheme { get; set; }
        public string CodeCallSource { get; set; }
        public string IPAddress { get; set; }
        public string UserAgent { get; set; }
        public int OrderSourceTypeId { get; set; }
        public string AmazonOrderId { get; set; }
        public bool IsFraud { get; set; }
        public Nullable<int> FraudReasonId { get; set; }
        public Nullable<System.DateTimeOffset> FraudSubmitDate { get; set; }
        public string FraudSubmitByUserID { get; set; }
        public bool FraudIncludeAccount { get; set; }
        public bool FraudIncludeShipAddress { get; set; }
        public bool FraudIncludeEmail { get; set; }
        public bool FraudIncludeContactPhone { get; set; }
        public bool FraudIncludeCustomerIP { get; set; }
        public string FraudOrderNotes { get; set; }
        public string FraudReasonNotes { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IPPEA_DATA_Checkout> IPPEA_DATA_Checkout { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IPPEA_DATA_ConversationOrderGroup> IPPEA_DATA_ConversationOrderGroup { get; set; }
        public virtual IPPEA_DATA_Customer IPPEA_DATA_Customer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IPPEA_DATA_EmailLog> IPPEA_DATA_EmailLog { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IPPEA_DATA_EmailQueue> IPPEA_DATA_EmailQueue { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IPPEA_DATA_FreightQuoteRequest> IPPEA_DATA_FreightQuoteRequest { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IPPEA_DATA_OrderCoupons> IPPEA_DATA_OrderCoupons { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IPPEA_DATA_OrderCustomerReviewStatus> IPPEA_DATA_OrderCustomerReviewStatus { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IPPEA_DATA_OrderFormHeader> IPPEA_DATA_OrderFormHeader { get; set; }
        public virtual IPPEA_DECODE_FraudReason IPPEA_DECODE_FraudReason { get; set; }
        public virtual IPPEA_DECODE_OrderStatus IPPEA_DECODE_OrderStatus { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IPPEA_DATA_ProductBlogMentions> IPPEA_DATA_ProductBlogMentions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IPPEA_DATA_ProductSocialMediaSubmission> IPPEA_DATA_ProductSocialMediaSubmission { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IPPEA_DATA_PTAuthorizations> IPPEA_DATA_PTAuthorizations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IPPEA_DATA_Quotes> IPPEA_DATA_Quotes { get; set; }
    }
}
