//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IPPEA.EntityData
{
    using System;
    using System.Collections.Generic;
    
    public partial class IPPEA_DATA_Customer_Archive
    {
        public int ArchiveID { get; set; }
        public string ArchiveType { get; set; }
        public string ArchiveReason { get; set; }
        public int ArchiveUserID { get; set; }
        public System.DateTimeOffset ArchiveDt { get; set; }
        public int ID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string CompanyName { get; set; }
        public bool Subscribed { get; set; }
        public System.DateTime DateCreated { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public bool IsINYOPool { get; set; }
        public bool IsINYOWinter { get; set; }
        public bool BypassCVVCheck { get; set; }
        public bool QandAQuestionOptOut { get; set; }
        public Nullable<System.DateTimeOffset> LastOnlineChatDate { get; set; }
        public Nullable<System.DateTimeOffset> LastSubscribedChangeDate { get; set; }
        public Nullable<int> LastSubscribedNewsletterGroupTypeId { get; set; }
        public string EmailAddress { get; set; }
        public Nullable<System.DateTime> LastBounceDate { get; set; }
        public Nullable<System.DateTime> LastComplaintDate { get; set; }
        public Nullable<System.DateTimeOffset> LastEmailChangeDate { get; set; }
        public Nullable<int> CreateTypeId { get; set; }
        public string UserId { get; set; }
        public Nullable<System.DateTimeOffset> LastSubscribedNewsletterGroupChangeDate { get; set; }
        public string FraudReason { get; set; }
        public string FraudReportedBy { get; set; }
        public Nullable<int> FraudStatusId { get; set; }
        public Nullable<System.DateTimeOffset> FraudReportedDate { get; set; }
    
        public virtual IPPEA_DATA_Employees IPPEA_DATA_Employees { get; set; }
    }
}
