//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IPPEA.EntityData
{
    using System;
    using System.Collections.Generic;
    
    public partial class IPPEA_DATA_OrderFormLineItem
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public IPPEA_DATA_OrderFormLineItem()
        {
            this.IPPEA_DATA_ProductPriceChange = new HashSet<IPPEA_DATA_ProductPriceChange>();
            this.IPPEA_DATA_ReturnItems = new HashSet<IPPEA_DATA_ReturnItems>();
            this.IPPEA_DATA_VendorInvoiceItem = new HashSet<IPPEA_DATA_VendorInvoiceItem>();
        }
    
        public int ID { get; set; }
        public int OrderFormID { get; set; }
        public int ProductID { get; set; }
        public string ProductName { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<decimal> UnitPrice { get; set; }
        public Nullable<decimal> TotalPrice { get; set; }
        public Nullable<decimal> UnitCost { get; set; }
        public Nullable<int> ShipMethodID { get; set; }
        public string AuctionNumber { get; set; }
        public string AuctionTransID { get; set; }
        public Nullable<int> ExpectedShipDay { get; set; }
        public int ItemStatusID { get; set; }
        public Nullable<System.DateTime> ShipDate { get; set; }
        public Nullable<int> VendorLocationID { get; set; }
        public Nullable<decimal> OriginalCost { get; set; }
        public string AuctionUser { get; set; }
        public System.DateTime LastChangeDate { get; set; }
        public Nullable<int> CancelReasonId { get; set; }
    
        public virtual IPPEA_DATA_OrderFormHeader IPPEA_DATA_OrderFormHeader { get; set; }
        public virtual IPPEA_DECODE_ItemStatus IPPEA_DECODE_ItemStatus { get; set; }
        public virtual IPPEA_DECODE_OrderItemCancelReasons IPPEA_DECODE_OrderItemCancelReasons { get; set; }
        public virtual IPPEA_DATA_Product IPPEA_DATA_Product { get; set; }
        public virtual IPPEA_DATA_ShipMethods IPPEA_DATA_ShipMethods { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IPPEA_DATA_ProductPriceChange> IPPEA_DATA_ProductPriceChange { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IPPEA_DATA_ReturnItems> IPPEA_DATA_ReturnItems { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IPPEA_DATA_VendorInvoiceItem> IPPEA_DATA_VendorInvoiceItem { get; set; }
    }
}
