//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IPPEA.EntityData
{
    using System;
    using System.Collections.Generic;
    
    public partial class IPPEA_DATA_Employees
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public IPPEA_DATA_Employees()
        {
            this.AspNetCustomers_Archive = new HashSet<AspNetCustomers_Archive>();
            this.AspNetEmployees = new HashSet<AspNetEmployee>();
            this.AspNetUserActivityLog_Archive = new HashSet<AspNetUserActivityLog_Archive>();
            this.AspNetUsers_Archive = new HashSet<AspNetUsers_Archive>();
            this.IP_DATA_HowToPageComments = new HashSet<IP_DATA_HowToPageComments>();
            this.IP_DATA_HowToPageComments1 = new HashSet<IP_DATA_HowToPageComments>();
            this.IP_DATA_HowToPageComments_Archive = new HashSet<IP_DATA_HowToPageComments_Archive>();
            this.IP_DATA_UserNickNames_Archive = new HashSet<IP_DATA_UserNickNames_Archive>();
            this.IPPEA_DATA_AccountsPayment_Archive = new HashSet<IPPEA_DATA_AccountsPayment_Archive>();
            this.IPPEA_DATA_AccountSummary_Archive = new HashSet<IPPEA_DATA_AccountSummary_Archive>();
            this.IPPEA_DATA_Addresses_Archive = new HashSet<IPPEA_DATA_Addresses_Archive>();
            this.IPPEA_DATA_AuthNetTransLog_Archive = new HashSet<IPPEA_DATA_AuthNetTransLog_Archive>();
            this.IPPEA_DATA_BillingOptions_Archive = new HashSet<IPPEA_DATA_BillingOptions_Archive>();
            this.IPPEA_DATA_BillMeLaterTransLog_Archive = new HashSet<IPPEA_DATA_BillMeLaterTransLog_Archive>();
            this.IPPEA_DATA_CheckoutItem_Archive = new HashSet<IPPEA_DATA_CheckoutItem_Archive>();
            this.IPPEA_DATA_CheckoutItemProduct_Archive = new HashSet<IPPEA_DATA_CheckoutItemProduct_Archive>();
            this.IPPEA_DATA_ConversationProductMentions_Archive = new HashSet<IPPEA_DATA_ConversationProductMentions_Archive>();
            this.IPPEA_DATA_CouponCodes_Archive = new HashSet<IPPEA_DATA_CouponCodes_Archive>();
            this.IPPEA_DATA_CouponProducts_Archive = new HashSet<IPPEA_DATA_CouponProducts_Archive>();
            this.IPPEA_DATA_Coupons_Archive = new HashSet<IPPEA_DATA_Coupons_Archive>();
            this.IPPEA_DATA_Customer_Archive = new HashSet<IPPEA_DATA_Customer_Archive>();
            this.IPPEA_DATA_Documents_Archive = new HashSet<IPPEA_DATA_Documents_Archive>();
            this.IPPEA_DATA_DoItYourselfStory = new HashSet<IPPEA_DATA_DoItYourselfStory>();
            this.IPPEA_DATA_DoItYourselfStory_Archive = new HashSet<IPPEA_DATA_DoItYourselfStory_Archive>();
            this.IPPEA_DATA_eBayListings_Archive = new HashSet<IPPEA_DATA_eBayListings_Archive>();
            this.IPPEA_DATA_eBayLogs_Archive = new HashSet<IPPEA_DATA_eBayLogs_Archive>();
            this.IPPEA_DATA_EmailAddress_Archive = new HashSet<IPPEA_DATA_EmailAddress_Archive>();
            this.IPPEA_DATA_EmailAttachments_Archive = new HashSet<IPPEA_DATA_EmailAttachments_Archive>();
            this.IPPEA_DATA_EmailLog = new HashSet<IPPEA_DATA_EmailLog>();
            this.IPPEA_DATA_EmailLog_Archive = new HashSet<IPPEA_DATA_EmailLog_Archive>();
            this.IPPEA_DATA_EmailQueue = new HashSet<IPPEA_DATA_EmailQueue>();
            this.IPPEA_DATA_EmailQueue_Archive = new HashSet<IPPEA_DATA_EmailQueue_Archive>();
            this.IPPEA_DATA_FileImports = new HashSet<IPPEA_DATA_FileImports>();
            this.IPPEA_DATA_HowToInformation_Archive = new HashSet<IPPEA_DATA_HowToInformation_Archive>();
            this.IPPEA_DATA_HowToPage_Archive = new HashSet<IPPEA_DATA_HowToPage_Archive>();
            this.IPPEA_DATA_HowToPageProductRelation_Archive = new HashSet<IPPEA_DATA_HowToPageProductRelation_Archive>();
            this.IPPEA_DATA_ManualProduct_Archive = new HashSet<IPPEA_DATA_ManualProduct_Archive>();
            this.IPPEA_DATA_MarketingList_Archive = new HashSet<IPPEA_DATA_MarketingList_Archive>();
            this.IPPEA_DATA_MergeProduct_Archive = new HashSet<IPPEA_DATA_MergeProduct_Archive>();
            this.IPPEA_DATA_MergeProduct = new HashSet<IPPEA_DATA_MergeProduct>();
            this.IPPEA_DATA_MergeProductLog_Archive = new HashSet<IPPEA_DATA_MergeProductLog_Archive>();
            this.IPPEA_DATA_MergeProductLog = new HashSet<IPPEA_DATA_MergeProductLog>();
            this.IPPEA_DATA_Notes_Archive = new HashSet<IPPEA_DATA_Notes_Archive>();
            this.IPPEA_DATA_OrderAssignment = new HashSet<IPPEA_DATA_OrderAssignment>();
            this.IPPEA_DATA_OrderAssignment1 = new HashSet<IPPEA_DATA_OrderAssignment>();
            this.IPPEA_DATA_OrderFormHeader_Archive = new HashSet<IPPEA_DATA_OrderFormHeader_Archive>();
            this.IPPEA_DATA_OrderFormHeader = new HashSet<IPPEA_DATA_OrderFormHeader>();
            this.IPPEA_DATA_OrderFormHeader1 = new HashSet<IPPEA_DATA_OrderFormHeader>();
            this.IPPEA_DATA_OrderFormLineItem_Archive = new HashSet<IPPEA_DATA_OrderFormLineItem_Archive>();
            this.IPPEA_DATA_OrderGroup_Archive = new HashSet<IPPEA_DATA_OrderGroup_Archive>();
            this.IPPEA_DATA_OutgoingFaxes_Archive = new HashSet<IPPEA_DATA_OutgoingFaxes_Archive>();
            this.IPPEA_DATA_PartChartRows_Archive = new HashSet<IPPEA_DATA_PartChartRows_Archive>();
            this.IPPEA_DATA_PartPages_Archive = new HashSet<IPPEA_DATA_PartPages_Archive>();
            this.IPPEA_DATA_PartProducts_Archive = new HashSet<IPPEA_DATA_PartProducts_Archive>();
            this.IPPEA_DATA_PartsShipRate_Archive = new HashSet<IPPEA_DATA_PartsShipRate_Archive>();
            this.IPPEA_DATA_PaymentTechTransLog_Archive = new HashSet<IPPEA_DATA_PaymentTechTransLog_Archive>();
            this.IPPEA_DATA_PayPalTransLog_Archive = new HashSet<IPPEA_DATA_PayPalTransLog_Archive>();
            this.IPPEA_DATA_PhoneNumbers_Archive = new HashSet<IPPEA_DATA_PhoneNumbers_Archive>();
            this.IPPEA_DATA_Product_Archive = new HashSet<IPPEA_DATA_Product_Archive>();
            this.IPPEA_DATA_ProductAlternatePartNumbers_Archive = new HashSet<IPPEA_DATA_ProductAlternatePartNumbers_Archive>();
            this.IPPEA_DATA_ProductAttribute_Archive = new HashSet<IPPEA_DATA_ProductAttribute_Archive>();
            this.IPPEA_DATA_ProductAttributeProducts_Archive = new HashSet<IPPEA_DATA_ProductAttributeProducts_Archive>();
            this.IPPEA_DATA_ProductAvailability_Archive = new HashSet<IPPEA_DATA_ProductAvailability_Archive>();
            this.IPPEA_DATA_ProductBlogMentions_Archive = new HashSet<IPPEA_DATA_ProductBlogMentions_Archive>();
            this.IPPEA_DATA_ProductCategory_Archive = new HashSet<IPPEA_DATA_ProductCategory_Archive>();
            this.IPPEA_DATA_ProductCustomerReviews_Archive = new HashSet<IPPEA_DATA_ProductCustomerReviews_Archive>();
            this.IPPEA_DATA_ProductMedia_Archive = new HashSet<IPPEA_DATA_ProductMedia_Archive>();
            this.IPPEA_DATA_ProductPackages_Archive = new HashSet<IPPEA_DATA_ProductPackages_Archive>();
            this.IPPEA_DATA_ProductPriceChange_Archive = new HashSet<IPPEA_DATA_ProductPriceChange_Archive>();
            this.IPPEA_DATA_ProductReviewRelation_Archive = new HashSet<IPPEA_DATA_ProductReviewRelation_Archive>();
            this.IPPEA_DATA_ProductShipMethods_Archive = new HashSet<IPPEA_DATA_ProductShipMethods_Archive>();
            this.IPPEA_DATA_ProductSocialMediaSubmission_Archive = new HashSet<IPPEA_DATA_ProductSocialMediaSubmission_Archive>();
            this.IPPEA_DATA_ProductSpecifications_Archive = new HashSet<IPPEA_DATA_ProductSpecifications_Archive>();
            this.IPPEA_DATA_ProductType_Archive = new HashSet<IPPEA_DATA_ProductType_Archive>();
            this.IPPEA_DATA_PromotionsEmail_Archive = new HashSet<IPPEA_DATA_PromotionsEmail_Archive>();
            this.IPPEA_DATA_PromotionsEmailsToSend_Archive = new HashSet<IPPEA_DATA_PromotionsEmailsToSend_Archive>();
            this.IPPEA_DATA_QandAAnswer_Archive = new HashSet<IPPEA_DATA_QandAAnswer_Archive>();
            this.IPPEA_DATA_QandAAnswer = new HashSet<IPPEA_DATA_QandAAnswer>();
            this.IPPEA_DATA_QandAAsked_Archive = new HashSet<IPPEA_DATA_QandAAsked_Archive>();
            this.IPPEA_DATA_QandAAsked = new HashSet<IPPEA_DATA_QandAAsked>();
            this.IPPEA_DATA_QandAProductOptOut_Archive = new HashSet<IPPEA_DATA_QandAProductOptOut_Archive>();
            this.IPPEA_DATA_QandAProducts_Archive = new HashSet<IPPEA_DATA_QandAProducts_Archive>();
            this.IPPEA_DATA_QandAQuestion_Archive = new HashSet<IPPEA_DATA_QandAQuestion_Archive>();
            this.IPPEA_DATA_QandAQuestion = new HashSet<IPPEA_DATA_QandAQuestion>();
            this.IPPEA_DATA_QandAQuestion1 = new HashSet<IPPEA_DATA_QandAQuestion>();
            this.IPPEA_DATA_QandAQuestion2 = new HashSet<IPPEA_DATA_QandAQuestion>();
            this.IPPEA_DATA_QuestionProduct_Archive = new HashSet<IPPEA_DATA_QuestionProduct_Archive>();
            this.IPPEA_DATA_QuoteItems_Archive = new HashSet<IPPEA_DATA_QuoteItems_Archive>();
            this.IPPEA_DATA_Quotes_Archive = new HashSet<IPPEA_DATA_Quotes_Archive>();
            this.IPPEA_DATA_Quotes = new HashSet<IPPEA_DATA_Quotes>();
            this.IPPEA_DATA_Recommendations_Archive = new HashSet<IPPEA_DATA_Recommendations_Archive>();
            this.IPPEA_DATA_SalesTaxExemption_Archive = new HashSet<IPPEA_DATA_SalesTaxExemption_Archive>();
            this.IPPEA_DATA_Session_Archive = new HashSet<IPPEA_DATA_Session_Archive>();
            this.IPPEA_DATA_ShipperExpenseDetail_Archive = new HashSet<IPPEA_DATA_ShipperExpenseDetail_Archive>();
            this.IPPEA_DATA_ShoppingCartItem_Archive = new HashSet<IPPEA_DATA_ShoppingCartItem_Archive>();
            this.IPPEA_DATA_SupportEmails = new HashSet<IPPEA_DATA_SupportEmails>();
            this.IPPEA_DATA_SupportTickets_Archive = new HashSet<IPPEA_DATA_SupportTickets_Archive>();
            this.IPPEA_DATA_SupportTickets = new HashSet<IPPEA_DATA_SupportTickets>();
            this.IPPEA_DATA_SupportTickets1 = new HashSet<IPPEA_DATA_SupportTickets>();
            this.IPPEA_DATA_SupportTickets2 = new HashSet<IPPEA_DATA_SupportTickets>();
            this.IPPEA_DATA_SupportTickets3 = new HashSet<IPPEA_DATA_SupportTickets>();
            this.IPPEA_DATA_TransLog_Archive = new HashSet<IPPEA_DATA_TransLog_Archive>();
            this.IPPEA_DATA_UrlRedirect_Archive = new HashSet<IPPEA_DATA_UrlRedirect_Archive>();
            this.IPPEA_DATA_UrlRewrite_Archive = new HashSet<IPPEA_DATA_UrlRewrite_Archive>();
            this.IPPEA_DATA_VendorBidServiceRelation_Archive = new HashSet<IPPEA_DATA_VendorBidServiceRelation_Archive>();
            this.IPPEA_DATA_VendorInvoice_Archive = new HashSet<IPPEA_DATA_VendorInvoice_Archive>();
            this.IPPEA_DATA_VendorInvoiceItem_Archive = new HashSet<IPPEA_DATA_VendorInvoiceItem_Archive>();
            this.IPPEA_DATA_VendorPriceRequest_Archive = new HashSet<IPPEA_DATA_VendorPriceRequest_Archive>();
            this.IPPEA_DATA_VendorProducts_Archive = new HashSet<IPPEA_DATA_VendorProducts_Archive>();
            this.IPPEA_DATA_WmsCarrierService_Archive = new HashSet<IPPEA_DATA_WmsCarrierService_Archive>();
            this.IPPEA_DATA_WmsJobLog_Archive = new HashSet<IPPEA_DATA_WmsJobLog_Archive>();
            this.IPPEA_DATA_WmsJobs_Archive = new HashSet<IPPEA_DATA_WmsJobs_Archive>();
            this.IPPEA_DATA_WmsOrderProduct_Archive = new HashSet<IPPEA_DATA_WmsOrderProduct_Archive>();
            this.IPPEA_DECODE_SupportCategories = new HashSet<IPPEA_DECODE_SupportCategories>();
        }
    
        public int ID { get; set; }
        public string SSNbr { get; set; }
        public string FirstName { get; set; }
        public string MiddleInitial { get; set; }
        public string LastName { get; set; }
        public string EmployeeTitle { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> EmployedSince { get; set; }
        public string EmailAddress { get; set; }
        public Nullable<System.DateTime> Birthdate { get; set; }
        public string Notes { get; set; }
        public Nullable<int> EmployeeStatusID { get; set; }
        public string UserName { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> RepPercent { get; set; }
        public Nullable<decimal> ReviewTicketCount { get; set; }
        public bool IsCollectionRep { get; set; }
        public bool IsNextCollectionrep { get; set; }
        public Nullable<int> DepartmentID { get; set; }
        public int IsProofRep { get; set; }
        public Nullable<int> Extension { get; set; }
        public bool ReceiveSupportTicketEmails { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AspNetCustomers_Archive> AspNetCustomers_Archive { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AspNetEmployee> AspNetEmployees { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AspNetUserActivityLog_Archive> AspNetUserActivityLog_Archive { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AspNetUsers_Archive> AspNetUsers_Archive { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IP_DATA_HowToPageComments> IP_DATA_HowToPageComments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IP_DATA_HowToPageComments> IP_DATA_HowToPageComments1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IP_DATA_HowToPageComments_Archive> IP_DATA_HowToPageComments_Archive { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IP_DATA_UserNickNames_Archive> IP_DATA_UserNickNames_Archive { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IPPEA_DATA_AccountsPayment_Archive> IPPEA_DATA_AccountsPayment_Archive { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IPPEA_DATA_AccountSummary_Archive> IPPEA_DATA_AccountSummary_Archive { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IPPEA_DATA_Addresses_Archive> IPPEA_DATA_Addresses_Archive { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IPPEA_DATA_AuthNetTransLog_Archive> IPPEA_DATA_AuthNetTransLog_Archive { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IPPEA_DATA_BillingOptions_Archive> IPPEA_DATA_BillingOptions_Archive { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IPPEA_DATA_BillMeLaterTransLog_Archive> IPPEA_DATA_BillMeLaterTransLog_Archive { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IPPEA_DATA_CheckoutItem_Archive> IPPEA_DATA_CheckoutItem_Archive { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IPPEA_DATA_CheckoutItemProduct_Archive> IPPEA_DATA_CheckoutItemProduct_Archive { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IPPEA_DATA_ConversationProductMentions_Archive> IPPEA_DATA_ConversationProductMentions_Archive { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IPPEA_DATA_CouponCodes_Archive> IPPEA_DATA_CouponCodes_Archive { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IPPEA_DATA_CouponProducts_Archive> IPPEA_DATA_CouponProducts_Archive { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IPPEA_DATA_Coupons_Archive> IPPEA_DATA_Coupons_Archive { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IPPEA_DATA_Customer_Archive> IPPEA_DATA_Customer_Archive { get; set; }
        public virtual IPPEA_DATA_Departments IPPEA_DATA_Departments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IPPEA_DATA_Documents_Archive> IPPEA_DATA_Documents_Archive { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IPPEA_DATA_DoItYourselfStory> IPPEA_DATA_DoItYourselfStory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IPPEA_DATA_DoItYourselfStory_Archive> IPPEA_DATA_DoItYourselfStory_Archive { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IPPEA_DATA_eBayListings_Archive> IPPEA_DATA_eBayListings_Archive { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IPPEA_DATA_eBayLogs_Archive> IPPEA_DATA_eBayLogs_Archive { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IPPEA_DATA_EmailAddress_Archive> IPPEA_DATA_EmailAddress_Archive { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IPPEA_DATA_EmailAttachments_Archive> IPPEA_DATA_EmailAttachments_Archive { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IPPEA_DATA_EmailLog> IPPEA_DATA_EmailLog { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IPPEA_DATA_EmailLog_Archive> IPPEA_DATA_EmailLog_Archive { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IPPEA_DATA_EmailQueue> IPPEA_DATA_EmailQueue { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IPPEA_DATA_EmailQueue_Archive> IPPEA_DATA_EmailQueue_Archive { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IPPEA_DATA_FileImports> IPPEA_DATA_FileImports { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IPPEA_DATA_HowToInformation_Archive> IPPEA_DATA_HowToInformation_Archive { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IPPEA_DATA_HowToPage_Archive> IPPEA_DATA_HowToPage_Archive { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IPPEA_DATA_HowToPageProductRelation_Archive> IPPEA_DATA_HowToPageProductRelation_Archive { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IPPEA_DATA_ManualProduct_Archive> IPPEA_DATA_ManualProduct_Archive { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IPPEA_DATA_MarketingList_Archive> IPPEA_DATA_MarketingList_Archive { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IPPEA_DATA_MergeProduct_Archive> IPPEA_DATA_MergeProduct_Archive { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IPPEA_DATA_MergeProduct> IPPEA_DATA_MergeProduct { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IPPEA_DATA_MergeProductLog_Archive> IPPEA_DATA_MergeProductLog_Archive { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IPPEA_DATA_MergeProductLog> IPPEA_DATA_MergeProductLog { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IPPEA_DATA_Notes_Archive> IPPEA_DATA_Notes_Archive { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IPPEA_DATA_OrderAssignment> IPPEA_DATA_OrderAssignment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IPPEA_DATA_OrderAssignment> IPPEA_DATA_OrderAssignment1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IPPEA_DATA_OrderFormHeader_Archive> IPPEA_DATA_OrderFormHeader_Archive { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IPPEA_DATA_OrderFormHeader> IPPEA_DATA_OrderFormHeader { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IPPEA_DATA_OrderFormHeader> IPPEA_DATA_OrderFormHeader1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IPPEA_DATA_OrderFormLineItem_Archive> IPPEA_DATA_OrderFormLineItem_Archive { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IPPEA_DATA_OrderGroup_Archive> IPPEA_DATA_OrderGroup_Archive { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IPPEA_DATA_OutgoingFaxes_Archive> IPPEA_DATA_OutgoingFaxes_Archive { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IPPEA_DATA_PartChartRows_Archive> IPPEA_DATA_PartChartRows_Archive { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IPPEA_DATA_PartPages_Archive> IPPEA_DATA_PartPages_Archive { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IPPEA_DATA_PartProducts_Archive> IPPEA_DATA_PartProducts_Archive { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IPPEA_DATA_PartsShipRate_Archive> IPPEA_DATA_PartsShipRate_Archive { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IPPEA_DATA_PaymentTechTransLog_Archive> IPPEA_DATA_PaymentTechTransLog_Archive { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IPPEA_DATA_PayPalTransLog_Archive> IPPEA_DATA_PayPalTransLog_Archive { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IPPEA_DATA_PhoneNumbers_Archive> IPPEA_DATA_PhoneNumbers_Archive { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IPPEA_DATA_Product_Archive> IPPEA_DATA_Product_Archive { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IPPEA_DATA_ProductAlternatePartNumbers_Archive> IPPEA_DATA_ProductAlternatePartNumbers_Archive { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IPPEA_DATA_ProductAttribute_Archive> IPPEA_DATA_ProductAttribute_Archive { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IPPEA_DATA_ProductAttributeProducts_Archive> IPPEA_DATA_ProductAttributeProducts_Archive { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IPPEA_DATA_ProductAvailability_Archive> IPPEA_DATA_ProductAvailability_Archive { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IPPEA_DATA_ProductBlogMentions_Archive> IPPEA_DATA_ProductBlogMentions_Archive { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IPPEA_DATA_ProductCategory_Archive> IPPEA_DATA_ProductCategory_Archive { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IPPEA_DATA_ProductCustomerReviews_Archive> IPPEA_DATA_ProductCustomerReviews_Archive { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IPPEA_DATA_ProductMedia_Archive> IPPEA_DATA_ProductMedia_Archive { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IPPEA_DATA_ProductPackages_Archive> IPPEA_DATA_ProductPackages_Archive { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IPPEA_DATA_ProductPriceChange_Archive> IPPEA_DATA_ProductPriceChange_Archive { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IPPEA_DATA_ProductReviewRelation_Archive> IPPEA_DATA_ProductReviewRelation_Archive { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IPPEA_DATA_ProductShipMethods_Archive> IPPEA_DATA_ProductShipMethods_Archive { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IPPEA_DATA_ProductSocialMediaSubmission_Archive> IPPEA_DATA_ProductSocialMediaSubmission_Archive { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IPPEA_DATA_ProductSpecifications_Archive> IPPEA_DATA_ProductSpecifications_Archive { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IPPEA_DATA_ProductType_Archive> IPPEA_DATA_ProductType_Archive { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IPPEA_DATA_PromotionsEmail_Archive> IPPEA_DATA_PromotionsEmail_Archive { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IPPEA_DATA_PromotionsEmailsToSend_Archive> IPPEA_DATA_PromotionsEmailsToSend_Archive { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IPPEA_DATA_QandAAnswer_Archive> IPPEA_DATA_QandAAnswer_Archive { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IPPEA_DATA_QandAAnswer> IPPEA_DATA_QandAAnswer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IPPEA_DATA_QandAAsked_Archive> IPPEA_DATA_QandAAsked_Archive { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IPPEA_DATA_QandAAsked> IPPEA_DATA_QandAAsked { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IPPEA_DATA_QandAProductOptOut_Archive> IPPEA_DATA_QandAProductOptOut_Archive { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IPPEA_DATA_QandAProducts_Archive> IPPEA_DATA_QandAProducts_Archive { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IPPEA_DATA_QandAQuestion_Archive> IPPEA_DATA_QandAQuestion_Archive { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IPPEA_DATA_QandAQuestion> IPPEA_DATA_QandAQuestion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IPPEA_DATA_QandAQuestion> IPPEA_DATA_QandAQuestion1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IPPEA_DATA_QandAQuestion> IPPEA_DATA_QandAQuestion2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IPPEA_DATA_QuestionProduct_Archive> IPPEA_DATA_QuestionProduct_Archive { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IPPEA_DATA_QuoteItems_Archive> IPPEA_DATA_QuoteItems_Archive { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IPPEA_DATA_Quotes_Archive> IPPEA_DATA_Quotes_Archive { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IPPEA_DATA_Quotes> IPPEA_DATA_Quotes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IPPEA_DATA_Recommendations_Archive> IPPEA_DATA_Recommendations_Archive { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IPPEA_DATA_SalesTaxExemption_Archive> IPPEA_DATA_SalesTaxExemption_Archive { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IPPEA_DATA_Session_Archive> IPPEA_DATA_Session_Archive { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IPPEA_DATA_ShipperExpenseDetail_Archive> IPPEA_DATA_ShipperExpenseDetail_Archive { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IPPEA_DATA_ShoppingCartItem_Archive> IPPEA_DATA_ShoppingCartItem_Archive { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IPPEA_DATA_SupportEmails> IPPEA_DATA_SupportEmails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IPPEA_DATA_SupportTickets_Archive> IPPEA_DATA_SupportTickets_Archive { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IPPEA_DATA_SupportTickets> IPPEA_DATA_SupportTickets { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IPPEA_DATA_SupportTickets> IPPEA_DATA_SupportTickets1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IPPEA_DATA_SupportTickets> IPPEA_DATA_SupportTickets2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IPPEA_DATA_SupportTickets> IPPEA_DATA_SupportTickets3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IPPEA_DATA_TransLog_Archive> IPPEA_DATA_TransLog_Archive { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IPPEA_DATA_UrlRedirect_Archive> IPPEA_DATA_UrlRedirect_Archive { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IPPEA_DATA_UrlRewrite_Archive> IPPEA_DATA_UrlRewrite_Archive { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IPPEA_DATA_VendorBidServiceRelation_Archive> IPPEA_DATA_VendorBidServiceRelation_Archive { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IPPEA_DATA_VendorInvoice_Archive> IPPEA_DATA_VendorInvoice_Archive { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IPPEA_DATA_VendorInvoiceItem_Archive> IPPEA_DATA_VendorInvoiceItem_Archive { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IPPEA_DATA_VendorPriceRequest_Archive> IPPEA_DATA_VendorPriceRequest_Archive { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IPPEA_DATA_VendorProducts_Archive> IPPEA_DATA_VendorProducts_Archive { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IPPEA_DATA_WmsCarrierService_Archive> IPPEA_DATA_WmsCarrierService_Archive { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IPPEA_DATA_WmsJobLog_Archive> IPPEA_DATA_WmsJobLog_Archive { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IPPEA_DATA_WmsJobs_Archive> IPPEA_DATA_WmsJobs_Archive { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IPPEA_DATA_WmsOrderProduct_Archive> IPPEA_DATA_WmsOrderProduct_Archive { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IPPEA_DECODE_SupportCategories> IPPEA_DECODE_SupportCategories { get; set; }
    }
}
