//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IPPEA.EntityData
{
    using System;
    using System.Collections.Generic;
    
    public partial class IPPEA_DATA_ProductCategoryRelated
    {
        public int ID { get; set; }
        public int CategoryID { get; set; }
        public int RelatedCategoryID { get; set; }
        public int SortOrder { get; set; }
    
        public virtual IPPEA_DATA_ProductCategory IPPEA_DATA_ProductCategory { get; set; }
        public virtual IPPEA_DATA_ProductCategory IPPEA_DATA_ProductCategory1 { get; set; }
    }
}
