//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IPPEA.EntityData
{
    using System;
    using System.Collections.Generic;
    
    public partial class IPPEA_DATA_FAQSearches
    {
        public int ID { get; set; }
        public string Question { get; set; }
        public string Subject { get; set; }
        public Nullable<bool> FromTicket { get; set; }
        public Nullable<bool> TicketSubmitted { get; set; }
        public Nullable<int> NumFAQs { get; set; }
        public Nullable<int> AffiliateID { get; set; }
        public Nullable<System.DateTime> DateEntered { get; set; }
    }
}
