//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IPPEA.EntityData
{
    using System;
    using System.Collections.Generic;
    
    public partial class IPPEA_DATA_SellingChannelActivity
    {
        public int Id { get; set; }
        public int SellingChannelId { get; set; }
        public int ActivityTypeId { get; set; }
        public System.Guid ActivityId { get; set; }
        public int ActivityStatusId { get; set; }
        public string Message { get; set; }
        public int ShipTrackingId { get; set; }
        public System.DateTimeOffset ActivityDate { get; set; }
        public string ActivityBy { get; set; }
    
        public virtual IPPEA_DECODE_ActivityStatus IPPEA_DECODE_ActivityStatus { get; set; }
        public virtual IPPEA_DECODE_ActivityTypes IPPEA_DECODE_ActivityTypes { get; set; }
        public virtual IPPEA_DECODE_SellingChannels IPPEA_DECODE_SellingChannels { get; set; }
        public virtual IPPEA_DATA_ShipTracking IPPEA_DATA_ShipTracking { get; set; }
    }
}
