//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IPPEA.EntityData
{
    using System;
    using System.Collections.Generic;
    
    public partial class IPPEA_DATA_MailUpBatchExport
    {
        public int Id { get; set; }
        public string EmailAddress { get; set; }
        public System.DateTimeOffset TriggerDate { get; set; }
        public int TriggerType { get; set; }
        public System.DateTimeOffset InsertDate { get; set; }
    }
}
