//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IPPEA.EntityData
{
    using System;
    using System.Collections.Generic;
    
    public partial class IPPEA_DATA_PromotionsEmail_Archive
    {
        public int ArchiveID { get; set; }
        public string ArchiveType { get; set; }
        public string ArchiveReason { get; set; }
        public int ArchiveUserID { get; set; }
        public System.DateTimeOffset ArchiveDt { get; set; }
        public int ID { get; set; }
        public string Email { get; set; }
        public int CustomerID { get; set; }
        public Nullable<int> PromotionsCriteriaID { get; set; }
        public Nullable<System.DateTime> DateSent { get; set; }
        public Nullable<bool> ValidEmail { get; set; }
        public Nullable<bool> Bounced { get; set; }
        public Nullable<bool> Opened { get; set; }
        public Nullable<int> OrderGroupID { get; set; }
        public string ProductIDs { get; set; }
    
        public virtual IPPEA_DATA_Employees IPPEA_DATA_Employees { get; set; }
    }
}
