//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IPPEA.EntityData
{
    using System;
    using System.Collections.Generic;
    
    public partial class IPPEA_DATA_VendorPriceUpdateResults
    {
        public int ID { get; set; }
        public int UpdateID { get; set; }
        public string ManufacturerCode { get; set; }
        public int MatchingProductCount { get; set; }
        public Nullable<decimal> PriceBeforeUpdate { get; set; }
        public decimal NewPrice { get; set; }
        public bool IsUpdated { get; set; }
        public bool RequiresManualReview { get; set; }
        public string UpdateNotes { get; set; }
    
        public virtual IPPEA_DATA_VendorPriceUpdate IPPEA_DATA_VendorPriceUpdate { get; set; }
    }
}
