//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IPPEA.EntityData
{
    using System;
    using System.Collections.Generic;
    
    public partial class IPPEA_DATA_CallTag
    {
        public int ID { get; set; }
        public Nullable<int> InvoiceID { get; set; }
        public Nullable<System.DateTime> EntryDate { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Zip { get; set; }
        public string Country { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public Nullable<double> Weight { get; set; }
        public string EmployeeUserName { get; set; }
        public string ActionToTake { get; set; }
        public Nullable<bool> Completed { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<System.DateTime> CompletedDate { get; set; }
        public string CompletedUserName { get; set; }
    }
}
