//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IPPEA.EntityData
{
    using System;
    using System.Collections.Generic;
    
    public partial class IPPEA_DATA_HowToInformation
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public IPPEA_DATA_HowToInformation()
        {
            this.IPPEA_DATA_HowToInformationMedia = new HashSet<IPPEA_DATA_HowToInformationMedia>();
        }
    
        public int ID { get; set; }
        public int SectionTypeID { get; set; }
        public int HowToPageID { get; set; }
        public string Description { get; set; }
        public bool IsDeleted { get; set; }
        public int Rank { get; set; }
        public string Link { get; set; }
        public string HtmlLink { get; set; }
        public string ImageFileName { get; set; }
        public string AltImageText { get; set; }
    
        public virtual IPPEA_DATA_HowToPage IPPEA_DATA_HowToPage { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IPPEA_DATA_HowToInformationMedia> IPPEA_DATA_HowToInformationMedia { get; set; }
    }
}
