//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IPPEA.EntityData
{
    using System;
    using System.Collections.Generic;
    
    public partial class IPPEA_DATA_Faxes
    {
        public int ID { get; set; }
        public Nullable<int> DocumentID { get; set; }
        public Nullable<int> ServiceRepID { get; set; }
        public Nullable<bool> Urgent { get; set; }
        public Nullable<bool> Closed { get; set; }
        public Nullable<int> AffiliateID { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
    }
}
