//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IPPEA.EntityData
{
    using System;
    using System.Collections.Generic;
    
    public partial class IPPEA_DATA_ProductGroupSpecifications
    {
        public int ID { get; set; }
        public int ProductGroupID { get; set; }
        public string SpecificationName { get; set; }
        public string SpecificationType { get; set; }
        public int ProductSpecificationDefinitionID { get; set; }
    
        public virtual IPPEA_DATA_ProductGroup IPPEA_DATA_ProductGroup { get; set; }
        public virtual IPPEA_DATA_ProductSpecificationDefinitions IPPEA_DATA_ProductSpecificationDefinitions { get; set; }
    }
}
