//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IPPEA.EntityData
{
    using System;
    using System.Collections.Generic;
    
    public partial class IPPEA_DATA_ReturnBatch
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public IPPEA_DATA_ReturnBatch()
        {
            this.IPPEA_DATA_ReturnItemsReceived = new HashSet<IPPEA_DATA_ReturnItemsReceived>();
        }
    
        public int ID { get; set; }
        public decimal Amount { get; set; }
        public bool CreditIssue { get; set; }
        public System.DateTime DateCreated { get; set; }
        public string CreditMemoNumber { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IPPEA_DATA_ReturnItemsReceived> IPPEA_DATA_ReturnItemsReceived { get; set; }
    }
}
