//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IPPEA.EntityData
{
    using System;
    using System.Collections.Generic;
    
    public partial class IPPEA_DATA_MarketingList
    {
        public int Id { get; set; }
        public int CustomerId { get; set; }
        public Nullable<int> MailUpRecipientId { get; set; }
        public string EmailAddress { get; set; }
        public int FailedAttempts { get; set; }
        public Nullable<System.DateTime> LastSyncDate { get; set; }
        public Nullable<System.DateTimeOffset> LastSubscriptionSyncDate { get; set; }
        public Nullable<int> LastNewsletterGroupTypeId { get; set; }
        public bool Subscribed { get; set; }
        public bool ExcludedFromMailUp { get; set; }
    
        public virtual IPPEA_DATA_Customer IPPEA_DATA_Customer { get; set; }
        public virtual IPPEA_DECODE_NewsletterGroupTypes IPPEA_DECODE_NewsletterGroupTypes { get; set; }
    }
}
