//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IPPEA.EntityData
{
    using System;
    using System.Collections.Generic;
    
    public partial class IPPEA_DATA_Addresses
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public IPPEA_DATA_Addresses()
        {
            this.IPPEA_DATA_BillingOptions = new HashSet<IPPEA_DATA_BillingOptions>();
        }
    
        public int ID { get; set; }
        public int AddressTypeID { get; set; }
        public int ObjectTypeID { get; set; }
        public int ObjectKey { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string CompanyName { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Zip { get; set; }
        public string Country { get; set; }
        public bool IsDeleted { get; set; }
        public bool IsDefault { get; set; }
        public bool DefaultBillTo { get; set; }
        public bool DefaultContact { get; set; }
        public bool DefaultShipTo { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<System.DateTime> DateUpdated { get; set; }
    
        public virtual IPPEA_DECODE_AddressType IPPEA_DECODE_AddressType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IPPEA_DATA_BillingOptions> IPPEA_DATA_BillingOptions { get; set; }
    }
}
