//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IPPEA.EntityData
{
    using System;
    using System.Collections.Generic;
    
    public partial class IPPEA_DATA_OrderFormHeader_Archive
    {
        public int ArchiveID { get; set; }
        public string ArchiveType { get; set; }
        public string ArchiveReason { get; set; }
        public int ArchiveUserID { get; set; }
        public System.DateTimeOffset ArchiveDt { get; set; }
        public int ID { get; set; }
        public int OrderGroupID { get; set; }
        public Nullable<System.DateTime> OrderFormDate { get; set; }
        public Nullable<int> OrderStatusID { get; set; }
        public Nullable<int> VendorID { get; set; }
        public Nullable<int> ServiceRepID { get; set; }
        public string ContactFirstName { get; set; }
        public string ContactLastName { get; set; }
        public string ContactCompany { get; set; }
        public string ContactAddress1 { get; set; }
        public string ContactAddress2 { get; set; }
        public string ContactCity { get; set; }
        public string ContactState { get; set; }
        public string ContactCountry { get; set; }
        public string ContactZip { get; set; }
        public string ContactPhone { get; set; }
        public string ContactFax { get; set; }
        public string ContactEmail { get; set; }
        public string BillToFirstName { get; set; }
        public string BillToLastName { get; set; }
        public string BillToCompany { get; set; }
        public string BillToAddress1 { get; set; }
        public string BillToAddress2 { get; set; }
        public string BillToCity { get; set; }
        public string BillToState { get; set; }
        public string BillToCountry { get; set; }
        public string BillToZip { get; set; }
        public string BillToPhone { get; set; }
        public string BillToFax { get; set; }
        public string BillToEmail { get; set; }
        public string ShipToFirstName { get; set; }
        public string ShiptoLastName { get; set; }
        public string ShipToCompany { get; set; }
        public string ShipToAddress1 { get; set; }
        public string ShipToAddress2 { get; set; }
        public string ShiptoCity { get; set; }
        public string ShipToState { get; set; }
        public string ShipToCountry { get; set; }
        public string ShipToZip { get; set; }
        public string ShipToPhone { get; set; }
        public string ShipToFax { get; set; }
        public string ShipToEmail { get; set; }
        public Nullable<int> InvoiceStatusID { get; set; }
        public Nullable<int> BillingTypeID { get; set; }
        public byte[] CCNumber { get; set; }
        public string CCID { get; set; }
        public string CCExpDate { get; set; }
        public string CCNameOnCard { get; set; }
        public string BAAccountName { get; set; }
        public string BABankName { get; set; }
        public byte[] BARoutingNumber { get; set; }
        public byte[] BAAccountNumber { get; set; }
        public string BACheckNumber { get; set; }
        public Nullable<decimal> BillTotal { get; set; }
        public Nullable<decimal> SubTotal { get; set; }
        public Nullable<decimal> TaxRate { get; set; }
        public Nullable<decimal> Shipping { get; set; }
        public Nullable<decimal> Handling { get; set; }
        public Nullable<int> ShipMethodID { get; set; }
        public Nullable<decimal> ShipTotal { get; set; }
        public Nullable<decimal> HandlingTotal { get; set; }
        public Nullable<decimal> Tax { get; set; }
        public string PPUserID { get; set; }
        public string ShipAccountNumber { get; set; }
        public string TaxCertificateNum { get; set; }
        public Nullable<bool> TaxCertificateOnFile { get; set; }
        public Nullable<System.DateTime> TaxCertificateExpDate { get; set; }
        public Nullable<bool> UseTaxCertificate { get; set; }
        public string PONumber { get; set; }
        public string UserID { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<System.DateTime> VendorDateApproved { get; set; }
        public Nullable<System.DateTime> VendorDateAccepted { get; set; }
        public Nullable<System.DateTime> VendorDateShipped { get; set; }
        public Nullable<bool> VendorAccepted { get; set; }
        public Nullable<decimal> AuthAmount { get; set; }
        public string AuthTransID { get; set; }
        public Nullable<bool> AuthCaptured { get; set; }
        public Nullable<System.DateTime> CostingDate { get; set; }
        public string CostingInvoiceNum { get; set; }
        public Nullable<decimal> ShippingCost { get; set; }
        public Nullable<decimal> TaxCost { get; set; }
        public string CostingUser { get; set; }
        public Nullable<decimal> SubTotalCost { get; set; }
        public Nullable<decimal> Totalcost { get; set; }
        public Nullable<int> BatchNum { get; set; }
        public Nullable<bool> PaidVendor { get; set; }
        public Nullable<System.DateTime> VendorDatePaid { get; set; }
        public Nullable<System.DateTime> DateCancelled { get; set; }
        public string UserCancelled { get; set; }
        public Nullable<int> VendorRequiredStatus { get; set; }
        public Nullable<System.DateTime> VendorRequiredExpectedShipDate { get; set; }
        public Nullable<System.DateTime> VendorRequiredLastSetDate { get; set; }
        public string AlternatePhoneNumber { get; set; }
        public string BMLCaptureRequestID { get; set; }
        public string BMLCaptureRequestToken { get; set; }
        public string IPAddress { get; set; }
        public Nullable<decimal> LiftGateFee { get; set; }
        public Nullable<int> CommercialAddress { get; set; }
        public Nullable<bool> SelectedLiftGate { get; set; }
        public Nullable<bool> UnishipperApiFailed { get; set; }
        public string PTCaptureRequestID { get; set; }
        public string PTCaptureRequestToken { get; set; }
        public Nullable<int> BAType { get; set; }
        public Nullable<decimal> PTCapturedAmount { get; set; }
        public Nullable<int> PTAuthorizationID { get; set; }
        public Nullable<bool> NoFreightBill { get; set; }
        public Nullable<bool> FreightBillToVendorInvoice { get; set; }
        public Nullable<bool> FreightBillToUPS { get; set; }
        public string GoogleOrderNumber { get; set; }
        public string GoogleBuyerID { get; set; }
        public string PPTransID { get; set; }
        public Nullable<int> AutoOrderStatusID { get; set; }
        public Nullable<bool> RefundHold { get; set; }
        public Nullable<System.DateTimeOffset> AuthCaptureDate { get; set; }
        public Nullable<bool> UsedNewVendorSelectionCriteria { get; set; }
        public string VendorSelectionComments { get; set; }
        public Nullable<System.DateTime> LMHRemovalDate { get; set; }
        public string LMHRemovalUser { get; set; }
        public Nullable<int> AuditReasonID { get; set; }
        public string AuditDetails { get; set; }
        public Nullable<int> AuditInitiatedBy { get; set; }
        public Nullable<System.DateTimeOffset> AuditInitiatedDate { get; set; }
        public Nullable<int> AuditResolvedBy { get; set; }
        public Nullable<System.DateTimeOffset> AuditResolvedDate { get; set; }
        public string AuditResolvedComments { get; set; }
        public Nullable<System.DateTimeOffset> VendorAutoSendDate { get; set; }
        public Nullable<int> LastPurchasingEvaluationId { get; set; }
    
        public virtual IPPEA_DATA_Employees IPPEA_DATA_Employees { get; set; }
    }
}
