//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IPPEA.EntityData
{
    using System;
    using System.Collections.Generic;
    
    public partial class IPPEA_DATA_ShipperExpenseDetail_Archive
    {
        public int ArchiveID { get; set; }
        public string ArchiveType { get; set; }
        public string ArchiveReason { get; set; }
        public int ArchiveUserID { get; set; }
        public System.DateTimeOffset ArchiveDt { get; set; }
        public int ID { get; set; }
        public string TrackingNumber { get; set; }
        public Nullable<int> CarrierID { get; set; }
        public Nullable<System.DateTime> InvoiceDate { get; set; }
        public string InvoiceNumber { get; set; }
        public Nullable<int> ServiceTypeID { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public int OrderFormID { get; set; }
        public Nullable<decimal> BillableWeight { get; set; }
        public Nullable<int> UPSCodeID { get; set; }
        public Nullable<int> CarrierInvoiceID { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<int> UPSFeeCategoryID { get; set; }
        public Nullable<int> UPSFeeCategoryDetailID { get; set; }
        public string UserName { get; set; }
    
        public virtual IPPEA_DATA_Employees IPPEA_DATA_Employees { get; set; }
    }
}
