//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IPPEA.EntityData
{
    using System;
    using System.Collections.Generic;
    
    public partial class IPPEA_DATA_ShoppingCartItem_Archive
    {
        public int ArchiveID { get; set; }
        public string ArchiveType { get; set; }
        public string ArchiveReason { get; set; }
        public int ArchiveUserID { get; set; }
        public System.DateTimeOffset ArchiveDt { get; set; }
        public int ID { get; set; }
        public Nullable<int> ProductID { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<decimal> UnitPrice { get; set; }
        public Nullable<int> CustomerID { get; set; }
        public Nullable<int> SessionID { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<int> OrderID { get; set; }
        public string AuctionNumber { get; set; }
        public string AuctionTransID { get; set; }
        public Nullable<int> ShipMethodID { get; set; }
        public string AuctionUser { get; set; }
        public string TemplateTheme { get; set; }
        public Nullable<short> ScreenResolutionWidth { get; set; }
        public Nullable<short> ScreenResolutionHeight { get; set; }
        public string IPAddress { get; set; }
        public string UserAgent { get; set; }
        public string InsertRawUrl { get; set; }
        public string SessionStateSessionID { get; set; }
        public Nullable<System.Guid> CartCookieID { get; set; }
    
        public virtual IPPEA_DATA_Employees IPPEA_DATA_Employees { get; set; }
    }
}
