//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IPPEA.EntityData
{
    using System;
    using System.Collections.Generic;
    
    public partial class IPPEA_DECODE_WmsJobType
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public IPPEA_DECODE_WmsJobType()
        {
            this.IPPEA_DATA_WmsJobLog = new HashSet<IPPEA_DATA_WmsJobLog>();
            this.IPPEA_DATA_WmsJobs = new HashSet<IPPEA_DATA_WmsJobs>();
        }
    
        public int Id { get; set; }
        public string Description { get; set; }
        public bool PauseOnFailure { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IPPEA_DATA_WmsJobLog> IPPEA_DATA_WmsJobLog { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IPPEA_DATA_WmsJobs> IPPEA_DATA_WmsJobs { get; set; }
    }
}
