//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IPPEA.EntityData
{
    using System;
    using System.Collections.Generic;
    
    public partial class IPPEA_DATA_PurchasingEvaluation
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public IPPEA_DATA_PurchasingEvaluation()
        {
            this.IPPEA_DATA_OrderFormHeader = new HashSet<IPPEA_DATA_OrderFormHeader>();
            this.IPPEA_DATA_PurchasingEvaluationDetails = new HashSet<IPPEA_DATA_PurchasingEvaluationDetails>();
        }
    
        public int Id { get; set; }
        public int OrderFormHeaderId { get; set; }
        public bool Passed { get; set; }
        public System.DateTimeOffset EvaluatedDate { get; set; }
        public string EvaluatedBy { get; set; }
        public System.DateTimeOffset FirstEvaluatedDate { get; set; }
        public string FirstEvaluatedBy { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IPPEA_DATA_OrderFormHeader> IPPEA_DATA_OrderFormHeader { get; set; }
        public virtual IPPEA_DATA_OrderFormHeader IPPEA_DATA_OrderFormHeader1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IPPEA_DATA_PurchasingEvaluationDetails> IPPEA_DATA_PurchasingEvaluationDetails { get; set; }
    }
}
