//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IPPEA.EntityData
{
    using System;
    using System.Collections.Generic;
    
    public partial class IPPEA_DATA_FileImports
    {
        public int Id { get; set; }
        public string FileName { get; set; }
        public string UploadedAsFileName { get; set; }
        public int StatusId { get; set; }
        public int ImportType { get; set; }
        public string Message { get; set; }
        public int EmployeeId { get; set; }
        public System.DateTimeOffset DateCreated { get; set; }
    
        public virtual IPPEA_DATA_Employees IPPEA_DATA_Employees { get; set; }
        public virtual IPPEA_DECODE_FileImportType IPPEA_DECODE_FileImportType { get; set; }
        public virtual IPPEA_DECODE_FileImportStatus IPPEA_DECODE_FileImportStatus { get; set; }
    }
}
