//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IPPEA.EntityData
{
    using System;
    using System.Collections.Generic;
    
    public partial class IPPEA_DATA_ProductSocialMediaSubmission
    {
        public int ID { get; set; }
        public int SocialMediaTypeID { get; set; }
        public int OrderGroupID { get; set; }
        public int ProductID { get; set; }
        public int CustomerID { get; set; }
        public System.DateTime SubmissionDate { get; set; }
        public Nullable<int> CouponCodeID { get; set; }
    
        public virtual IPPEA_DATA_Customer IPPEA_DATA_Customer { get; set; }
        public virtual IPPEA_DATA_OrderGroup IPPEA_DATA_OrderGroup { get; set; }
        public virtual IPPEA_DATA_Product IPPEA_DATA_Product { get; set; }
        public virtual IPPEA_DECODE_SocialMediaType IPPEA_DECODE_SocialMediaType { get; set; }
    }
}
