//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IPPEA.EntityData
{
    using System;
    using System.Collections.Generic;
    
    public partial class IPPEA_DATA_Customer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public IPPEA_DATA_Customer()
        {
            this.AspNetCustomers = new HashSet<AspNetCustomer>();
            this.IP_DATA_HowToPageComments = new HashSet<IP_DATA_HowToPageComments>();
            this.IP_DATA_UserNickNames = new HashSet<IP_DATA_UserNickNames>();
            this.IPPEA_DATA_AccountsPayment = new HashSet<IPPEA_DATA_AccountsPayment>();
            this.IPPEA_DATA_AccountSummary = new HashSet<IPPEA_DATA_AccountSummary>();
            this.IPPEA_DATA_AuthNetTransLog = new HashSet<IPPEA_DATA_AuthNetTransLog>();
            this.IPPEA_DATA_BillingOptions = new HashSet<IPPEA_DATA_BillingOptions>();
            this.IPPEA_DATA_BillMeLaterTransLog = new HashSet<IPPEA_DATA_BillMeLaterTransLog>();
            this.IPPEA_DATA_Checkout = new HashSet<IPPEA_DATA_Checkout>();
            this.IPPEA_DATA_CouponCodes = new HashSet<IPPEA_DATA_CouponCodes>();
            this.IPPEA_DATA_Coupons = new HashSet<IPPEA_DATA_Coupons>();
            this.IPPEA_DATA_Documents = new HashSet<IPPEA_DATA_Documents>();
            this.IPPEA_DATA_DoItYourselfStory = new HashSet<IPPEA_DATA_DoItYourselfStory>();
            this.IPPEA_DATA_EmailLog = new HashSet<IPPEA_DATA_EmailLog>();
            this.IPPEA_DATA_EmailQueue = new HashSet<IPPEA_DATA_EmailQueue>();
            this.IPPEA_DATA_MarketingList = new HashSet<IPPEA_DATA_MarketingList>();
            this.IPPEA_DATA_OrderGroup = new HashSet<IPPEA_DATA_OrderGroup>();
            this.IPPEA_DATA_OutgoingFaxes = new HashSet<IPPEA_DATA_OutgoingFaxes>();
            this.IPPEA_DATA_PaymentTechTransLog = new HashSet<IPPEA_DATA_PaymentTechTransLog>();
            this.IPPEA_DATA_PayPalTransLog = new HashSet<IPPEA_DATA_PayPalTransLog>();
            this.IPPEA_DATA_ProductAvailability = new HashSet<IPPEA_DATA_ProductAvailability>();
            this.IPPEA_DATA_ProductBlogMentions = new HashSet<IPPEA_DATA_ProductBlogMentions>();
            this.IPPEA_DATA_ProductCustomerReviews = new HashSet<IPPEA_DATA_ProductCustomerReviews>();
            this.IPPEA_DATA_ProductSocialMediaSubmission = new HashSet<IPPEA_DATA_ProductSocialMediaSubmission>();
            this.IPPEA_DATA_PromotionsEmail = new HashSet<IPPEA_DATA_PromotionsEmail>();
            this.IPPEA_DATA_PromotionsEmailsToSend = new HashSet<IPPEA_DATA_PromotionsEmailsToSend>();
            this.IPPEA_DATA_QandAAnswer = new HashSet<IPPEA_DATA_QandAAnswer>();
            this.IPPEA_DATA_QandAAsked = new HashSet<IPPEA_DATA_QandAAsked>();
            this.IPPEA_DATA_QandAProductOptOut = new HashSet<IPPEA_DATA_QandAProductOptOut>();
            this.IPPEA_DATA_QandAQuestion = new HashSet<IPPEA_DATA_QandAQuestion>();
            this.IPPEA_DATA_Quotes = new HashSet<IPPEA_DATA_Quotes>();
            this.IPPEA_DATA_SalesTaxExemption = new HashSet<IPPEA_DATA_SalesTaxExemption>();
            this.IPPEA_DATA_Session = new HashSet<IPPEA_DATA_Session>();
            this.IPPEA_DATA_ShoppingCartItem = new HashSet<IPPEA_DATA_ShoppingCartItem>();
            this.IPPEA_DATA_SupportTickets = new HashSet<IPPEA_DATA_SupportTickets>();
        }
    
        public int ID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string CompanyName { get; set; }
        public bool Subscribed { get; set; }
        public System.DateTime DateCreated { get; set; }
        public bool IsINYOPool { get; set; }
        public bool IsINYOWinter { get; set; }
        public bool BypassCVVCheck { get; set; }
        public bool QandAQuestionOptOut { get; set; }
        public Nullable<System.DateTimeOffset> LastOnlineChatDate { get; set; }
        public Nullable<System.DateTimeOffset> LastSubscribedChangeDate { get; set; }
        public Nullable<int> LastSubscribedNewsletterGroupTypeId { get; set; }
        public string EmailAddress { get; set; }
        public Nullable<System.DateTime> LastBounceDate { get; set; }
        public Nullable<System.DateTime> LastComplaintDate { get; set; }
        public Nullable<System.DateTimeOffset> LastEmailChangeDate { get; set; }
        public Nullable<int> CreateTypeId { get; set; }
        public string UserId { get; set; }
        public Nullable<System.DateTimeOffset> LastSubscribedNewsletterGroupChangeDate { get; set; }
        public string FraudReason { get; set; }
        public string FraudReportedBy { get; set; }
        public Nullable<int> FraudStatusId { get; set; }
        public Nullable<System.DateTimeOffset> FraudReportedDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AspNetCustomer> AspNetCustomers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IP_DATA_HowToPageComments> IP_DATA_HowToPageComments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IP_DATA_UserNickNames> IP_DATA_UserNickNames { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IPPEA_DATA_AccountsPayment> IPPEA_DATA_AccountsPayment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IPPEA_DATA_AccountSummary> IPPEA_DATA_AccountSummary { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IPPEA_DATA_AuthNetTransLog> IPPEA_DATA_AuthNetTransLog { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IPPEA_DATA_BillingOptions> IPPEA_DATA_BillingOptions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IPPEA_DATA_BillMeLaterTransLog> IPPEA_DATA_BillMeLaterTransLog { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IPPEA_DATA_Checkout> IPPEA_DATA_Checkout { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IPPEA_DATA_CouponCodes> IPPEA_DATA_CouponCodes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IPPEA_DATA_Coupons> IPPEA_DATA_Coupons { get; set; }
        public virtual IPPEA_DECODE_CustomerCreateTypes IPPEA_DECODE_CustomerCreateTypes { get; set; }
        public virtual IPPEA_DECODE_FraudStatus IPPEA_DECODE_FraudStatus { get; set; }
        public virtual IPPEA_DECODE_NewsletterGroupTypes IPPEA_DECODE_NewsletterGroupTypes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IPPEA_DATA_Documents> IPPEA_DATA_Documents { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IPPEA_DATA_DoItYourselfStory> IPPEA_DATA_DoItYourselfStory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IPPEA_DATA_EmailLog> IPPEA_DATA_EmailLog { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IPPEA_DATA_EmailQueue> IPPEA_DATA_EmailQueue { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IPPEA_DATA_MarketingList> IPPEA_DATA_MarketingList { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IPPEA_DATA_OrderGroup> IPPEA_DATA_OrderGroup { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IPPEA_DATA_OutgoingFaxes> IPPEA_DATA_OutgoingFaxes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IPPEA_DATA_PaymentTechTransLog> IPPEA_DATA_PaymentTechTransLog { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IPPEA_DATA_PayPalTransLog> IPPEA_DATA_PayPalTransLog { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IPPEA_DATA_ProductAvailability> IPPEA_DATA_ProductAvailability { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IPPEA_DATA_ProductBlogMentions> IPPEA_DATA_ProductBlogMentions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IPPEA_DATA_ProductCustomerReviews> IPPEA_DATA_ProductCustomerReviews { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IPPEA_DATA_ProductSocialMediaSubmission> IPPEA_DATA_ProductSocialMediaSubmission { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IPPEA_DATA_PromotionsEmail> IPPEA_DATA_PromotionsEmail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IPPEA_DATA_PromotionsEmailsToSend> IPPEA_DATA_PromotionsEmailsToSend { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IPPEA_DATA_QandAAnswer> IPPEA_DATA_QandAAnswer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IPPEA_DATA_QandAAsked> IPPEA_DATA_QandAAsked { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IPPEA_DATA_QandAProductOptOut> IPPEA_DATA_QandAProductOptOut { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IPPEA_DATA_QandAQuestion> IPPEA_DATA_QandAQuestion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IPPEA_DATA_Quotes> IPPEA_DATA_Quotes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IPPEA_DATA_SalesTaxExemption> IPPEA_DATA_SalesTaxExemption { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IPPEA_DATA_Session> IPPEA_DATA_Session { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IPPEA_DATA_ShoppingCartItem> IPPEA_DATA_ShoppingCartItem { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IPPEA_DATA_SupportTickets> IPPEA_DATA_SupportTickets { get; set; }
    }
}
