//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IPPEA.EntityData
{
    using System;
    using System.Collections.Generic;
    
    public partial class IPPEA_DECODE_Countries
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public IPPEA_DECODE_Countries()
        {
            this.IPPEA_DATA_Checkout = new HashSet<IPPEA_DATA_Checkout>();
            this.IPPEA_DATA_Checkout1 = new HashSet<IPPEA_DATA_Checkout>();
            this.IPPEA_DECODE_CountryStateProvinceCode = new HashSet<IPPEA_DECODE_CountryStateProvinceCode>();
        }
    
        public int ID { get; set; }
        public string Description { get; set; }
        public int SortOrder { get; set; }
        public string CountryCode { get; set; }
        public bool HasPostalCode { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IPPEA_DATA_Checkout> IPPEA_DATA_Checkout { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IPPEA_DATA_Checkout> IPPEA_DATA_Checkout1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IPPEA_DECODE_CountryStateProvinceCode> IPPEA_DECODE_CountryStateProvinceCode { get; set; }
    }
}
