//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IPPEA.EntityData
{
    using System;
    using System.Collections.Generic;
    
    public partial class IPPEA_DATA_WmsProductLocation
    {
        public int Id { get; set; }
        public int VendorId { get; set; }
        public int VendorLocationId { get; set; }
        public string ManufacturerCode { get; set; }
        public string Location { get; set; }
        public System.DateTimeOffset LastUpdatedDt { get; set; }
    }
}
