//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IPPEA.EntityData
{
    using System;
    using System.Collections.Generic;
    
    public partial class IPPEA_DATA_ShipperExpenseDetail
    {
        public int ID { get; set; }
        public string TrackingNumber { get; set; }
        public int CarrierID { get; set; }
        public Nullable<System.DateTime> InvoiceDate { get; set; }
        public string InvoiceNumber { get; set; }
        public int ServiceTypeID { get; set; }
        public decimal Amount { get; set; }
        public int OrderFormID { get; set; }
        public Nullable<decimal> BillableWeight { get; set; }
        public Nullable<int> UPSCodeID { get; set; }
        public Nullable<int> CarrierInvoiceID { get; set; }
        public System.DateTime DateCreated { get; set; }
        public Nullable<int> UPSFeeCategoryID { get; set; }
        public Nullable<int> UPSFeeCategoryDetailID { get; set; }
        public string UserName { get; set; }
    
        public virtual IPPEA_DATA_OrderFormHeader IPPEA_DATA_OrderFormHeader { get; set; }
        public virtual IPPEA_DATA_ShipCarriers IPPEA_DATA_ShipCarriers { get; set; }
    }
}
