//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IPPEA.EntityData
{
    using System;
    using System.Collections.Generic;
    
    public partial class IPPEA_DATA_BillMeLaterSettings
    {
        public int ID { get; set; }
        public string Description { get; set; }
        public Nullable<decimal> MinOrderTotal { get; set; }
        public string ItemCategory { get; set; }
        public string DeliveryType { get; set; }
        public string TCWebCode { get; set; }
        public string TCCallCode { get; set; }
        public string DivisionCoreNum { get; set; }
        public string DivisionPromotionNum { get; set; }
        public string CardType { get; set; }
        public string CardExpirationMonth { get; set; }
        public string CardexpirationYear { get; set; }
        public string CardAccountNumber { get; set; }
        public string MerchantID { get; set; }
        public string MerchantPromo90ID { get; set; }
        public string Promo90Message { get; set; }
        public Nullable<bool> Promo90InUse { get; set; }
        public Nullable<bool> InUse { get; set; }
        public string CCMerchantID { get; set; }
        public Nullable<int> DivisionCCNum { get; set; }
        public Nullable<bool> CCTestMode { get; set; }
        public string PTKeyFileName { get; set; }
        public string AliasIDCore { get; set; }
        public string AliasIDPromotion { get; set; }
        public string RequestURL { get; set; }
        public string InterimURL { get; set; }
        public string UpdateURL { get; set; }
        public string MethodOfPaymentURL { get; set; }
    }
}
