//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IPPEA.EntityData
{
    using System;
    using System.Collections.Generic;
    
    public partial class IPPEA_DATA_PaymentTechTransLog_Archive
    {
        public int ArchiveID { get; set; }
        public string ArchiveType { get; set; }
        public string ArchiveReason { get; set; }
        public int ArchiveUserID { get; set; }
        public System.DateTimeOffset ArchiveDt { get; set; }
        public int ID { get; set; }
        public string Decision { get; set; }
        public Nullable<int> CustomerID { get; set; }
        public Nullable<int> OrderFormID { get; set; }
        public Nullable<int> ReplyType { get; set; }
        public Nullable<int> AuthorizationID { get; set; }
        public string AuthCode { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<System.DateTime> DateEntered { get; set; }
        public Nullable<int> ReasonCode { get; set; }
        public string ReconciliationID { get; set; }
        public string RequestID { get; set; }
        public string CCExpDate { get; set; }
        public byte[] CCNumber { get; set; }
        public string BABankName { get; set; }
        public string BAAcountName { get; set; }
        public byte[] BARoutingNumber { get; set; }
        public byte[] BAAcountNumber { get; set; }
        public Nullable<int> BillingTypeID { get; set; }
        public Nullable<int> TranTypeID { get; set; }
        public string UserID { get; set; }
        public string RequestToken { get; set; }
        public string MissingFields { get; set; }
        public string InvalidFields { get; set; }
        public string AvsCode { get; set; }
        public string AvsCodeRaw { get; set; }
        public string ProcessorResponse { get; set; }
        public string CavvResponseCode { get; set; }
        public string CavvResponseCodeRaw { get; set; }
        public string CvCode { get; set; }
        public string CvCodeRaw { get; set; }
        public string MerchantAdviceCode { get; set; }
        public string MerchantAdviceCodeRaw { get; set; }
        public Nullable<int> AfsResult { get; set; }
    
        public virtual IPPEA_DATA_Employees IPPEA_DATA_Employees { get; set; }
    }
}
