//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IPPEA.EntityData
{
    using System;
    using System.Collections.Generic;
    
    public partial class IPPEA_DATA_AmazonOrders
    {
        public int Id { get; set; }
        public long BatchId { get; set; }
        public bool IsExcluded { get; set; }
        public string OrderId { get; set; }
        public string OrderItemId { get; set; }
        public string PurchaseDate { get; set; }
        public string PaymentsDate { get; set; }
        public string Sku { get; set; }
        public string ProductName { get; set; }
        public int QuantityPurchased { get; set; }
        public string Currency { get; set; }
        public decimal ItemPrice { get; set; }
        public decimal ShippingPrice { get; set; }
        public string ShipService { get; set; }
        public string RecipientName { get; set; }
        public string ShipAddress1 { get; set; }
        public string ShipAddress2 { get; set; }
        public string ShipCity { get; set; }
        public string ShipState { get; set; }
        public string ShipPostalCode { get; set; }
        public string ShipCountry { get; set; }
        public string ShipPhoneNumber { get; set; }
        public string DeliveryInstructions { get; set; }
        public string IsBusinessOrder { get; set; }
    }
}
