//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IPPEA.EntityData
{
    using System;
    using System.Collections.Generic;
    
    public partial class IPPEA_DATA_PromotionsEmailsToSend
    {
        public int ID { get; set; }
        public string Email { get; set; }
        public int CustomerID { get; set; }
        public int PromotionsCriteriaID { get; set; }
    
        public virtual IPPEA_DATA_Customer IPPEA_DATA_Customer { get; set; }
        public virtual IPPEA_DATA_PromotionsCriteria IPPEA_DATA_PromotionsCriteria { get; set; }
    }
}
