//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IPPEA.EntityData
{
    using System;
    using System.Collections.Generic;
    
    public partial class IPPEA_DECODE_AuthNetResponses
    {
        public int ID { get; set; }
        public Nullable<int> ResponseCode { get; set; }
        public Nullable<int> ResponseReasonCode { get; set; }
        public string ResponseReasonText { get; set; }
    }
}
