//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IPPEA.EntityData
{
    using System;
    using System.Collections.Generic;
    
    public partial class IPPEA_DATA_DataChangeLog
    {
        public int Id { get; set; }
        public System.Guid EventID { get; set; }
        public string RecordChangeType { get; set; }
        public string Reason { get; set; }
        public string UserName { get; set; }
        public System.DateTimeOffset ChangeDate { get; set; }
        public string TableName { get; set; }
        public string ColumnName { get; set; }
        public string OldValueLarge { get; set; }
        public string NewValueLarge { get; set; }
    }
}
