//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IPPEA.EntityData
{
    using System;
    using System.Collections.Generic;
    
    public partial class IPPEA_DATA_ShipMethods
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public IPPEA_DATA_ShipMethods()
        {
            this.IPPEA_DATA_Checkout = new HashSet<IPPEA_DATA_Checkout>();
            this.IPPEA_DATA_CheckoutShippingMethod = new HashSet<IPPEA_DATA_CheckoutShippingMethod>();
            this.IPPEA_DATA_OrderFormHeader = new HashSet<IPPEA_DATA_OrderFormHeader>();
            this.IPPEA_DATA_OrderFormLineItem = new HashSet<IPPEA_DATA_OrderFormLineItem>();
            this.IPPEA_DATA_QuoteItems = new HashSet<IPPEA_DATA_QuoteItems>();
            this.IPPEA_DATA_Quotes = new HashSet<IPPEA_DATA_Quotes>();
            this.IPPEA_DATA_VendorShipMethods = new HashSet<IPPEA_DATA_VendorShipMethods>();
            this.IPPEA_DATA_WmsCarrierService = new HashSet<IPPEA_DATA_WmsCarrierService>();
        }
    
        public int ID { get; set; }
        public Nullable<int> CarrierID { get; set; }
        public string Description { get; set; }
        public decimal Multiplier { get; set; }
        public string RateTable { get; set; }
        public string RateName { get; set; }
        public bool ContUS { get; set; }
        public bool AlaskaHawaii { get; set; }
        public bool APO { get; set; }
        public bool Canada { get; set; }
        public bool International { get; set; }
        public bool PuertoRico { get; set; }
        public bool Custom { get; set; }
        public int SortOrder { get; set; }
        public bool IsExpedited { get; set; }
        public decimal FuelSurchargePct { get; set; }
        public Nullable<int> OptimusXMLServiceCode { get; set; }
        public Nullable<int> BelAquaServiceCode { get; set; }
        public string APCbaystateServiceCode { get; set; }
        public string UPSServiceCode { get; set; }
        public string UPSServiceName { get; set; }
        public string DeliveryCommitment { get; set; }
        public string Disclaimer { get; set; }
        public bool PublicOption { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IPPEA_DATA_Checkout> IPPEA_DATA_Checkout { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IPPEA_DATA_CheckoutShippingMethod> IPPEA_DATA_CheckoutShippingMethod { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IPPEA_DATA_OrderFormHeader> IPPEA_DATA_OrderFormHeader { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IPPEA_DATA_OrderFormLineItem> IPPEA_DATA_OrderFormLineItem { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IPPEA_DATA_QuoteItems> IPPEA_DATA_QuoteItems { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IPPEA_DATA_Quotes> IPPEA_DATA_Quotes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IPPEA_DATA_VendorShipMethods> IPPEA_DATA_VendorShipMethods { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IPPEA_DATA_WmsCarrierService> IPPEA_DATA_WmsCarrierService { get; set; }
    }
}
