//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IPPEA.EntityData
{
    using System;
    using System.Collections.Generic;
    
    public partial class IPPEA_DECODE_CountryStateProvinceCode
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public IPPEA_DECODE_CountryStateProvinceCode()
        {
            this.IPPEA_DATA_Checkout = new HashSet<IPPEA_DATA_Checkout>();
            this.IPPEA_DATA_Checkout1 = new HashSet<IPPEA_DATA_Checkout>();
            this.IPPEA_DATA_SalesTaxExemption = new HashSet<IPPEA_DATA_SalesTaxExemption>();
        }
    
        public int ID { get; set; }
        public string CountryCode { get; set; }
        public string StateProvinceName { get; set; }
        public string StateProvinceCode { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IPPEA_DATA_Checkout> IPPEA_DATA_Checkout { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IPPEA_DATA_Checkout> IPPEA_DATA_Checkout1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IPPEA_DATA_SalesTaxExemption> IPPEA_DATA_SalesTaxExemption { get; set; }
        public virtual IPPEA_DECODE_Countries IPPEA_DECODE_Countries { get; set; }
    }
}
