//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IPPEA.EntityData
{
    using System;
    using System.Collections.Generic;
    
    public partial class IPPEA_DATA_ReturnItems
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public IPPEA_DATA_ReturnItems()
        {
            this.IPPEA_DATA_ReturnItemsReceived = new HashSet<IPPEA_DATA_ReturnItemsReceived>();
        }
    
        public int ID { get; set; }
        public int ReturnID { get; set; }
        public int OrderFormLineItemID { get; set; }
        public int ReturnReasonID { get; set; }
        public int Quantity { get; set; }
        public decimal Amount { get; set; }
        public decimal RestockFee { get; set; }
        public decimal Shipping { get; set; }
        public decimal Tax { get; set; }
        public Nullable<int> PickUpID { get; set; }
        public Nullable<int> CustomerCredit { get; set; }
    
        public virtual IPPEA_DATA_OrderFormLineItem IPPEA_DATA_OrderFormLineItem { get; set; }
        public virtual IPPEA_DECODE_PickUp IPPEA_DECODE_PickUp { get; set; }
        public virtual IPPEA_DATA_Returns IPPEA_DATA_Returns { get; set; }
        public virtual IPPEA_DECODE_ReturnReason IPPEA_DECODE_ReturnReason { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IPPEA_DATA_ReturnItemsReceived> IPPEA_DATA_ReturnItemsReceived { get; set; }
    }
}
