//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IPPEA.EntityData
{
    using System;
    using System.Collections.Generic;
    
    public partial class IPPEA_DATA_Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public IPPEA_DATA_Product()
        {
            this.IPPEA_DATA_CheckoutItem = new HashSet<IPPEA_DATA_CheckoutItem>();
            this.IPPEA_DATA_CheckoutItemProduct = new HashSet<IPPEA_DATA_CheckoutItemProduct>();
            this.IPPEA_DATA_ConversationProductMentions = new HashSet<IPPEA_DATA_ConversationProductMentions>();
            this.IPPEA_DATA_CouponProducts = new HashSet<IPPEA_DATA_CouponProducts>();
            this.IPPEA_DATA_DoItYourselfStory = new HashSet<IPPEA_DATA_DoItYourselfStory>();
            this.IPPEA_DATA_DoItYourselfStoryProducts = new HashSet<IPPEA_DATA_DoItYourselfStoryProducts>();
            this.IPPEA_DATA_eBayListings = new HashSet<IPPEA_DATA_eBayListings>();
            this.IPPEA_DATA_eBayLogs = new HashSet<IPPEA_DATA_eBayLogs>();
            this.IPPEA_DATA_HowToPageProductRelation = new HashSet<IPPEA_DATA_HowToPageProductRelation>();
            this.IPPEA_DATA_ManualProduct = new HashSet<IPPEA_DATA_ManualProduct>();
            this.IPPEA_DATA_MergeProduct = new HashSet<IPPEA_DATA_MergeProduct>();
            this.IPPEA_DATA_MergeProductLog = new HashSet<IPPEA_DATA_MergeProductLog>();
            this.IPPEA_DATA_OrderFormLineItem = new HashSet<IPPEA_DATA_OrderFormLineItem>();
            this.IPPEA_DATA_PartChartRows = new HashSet<IPPEA_DATA_PartChartRows>();
            this.IPPEA_DATA_PartProducts = new HashSet<IPPEA_DATA_PartProducts>();
            this.IPPEA_DATA_ProductAccessories = new HashSet<IPPEA_DATA_ProductAccessories>();
            this.IPPEA_DATA_ProductAccessories1 = new HashSet<IPPEA_DATA_ProductAccessories>();
            this.IPPEA_DATA_ProductAlternatePartNumbers = new HashSet<IPPEA_DATA_ProductAlternatePartNumbers>();
            this.IPPEA_DATA_ProductAttributeProducts = new HashSet<IPPEA_DATA_ProductAttributeProducts>();
            this.IPPEA_DATA_ProductAvailability = new HashSet<IPPEA_DATA_ProductAvailability>();
            this.IPPEA_DATA_ProductFeedGoogle = new HashSet<IPPEA_DATA_ProductFeedGoogle>();
            this.IPPEA_DATA_ProductMedia = new HashSet<IPPEA_DATA_ProductMedia>();
            this.IPPEA_DATA_ProductPackages = new HashSet<IPPEA_DATA_ProductPackages>();
            this.IPPEA_DATA_ProductPackages1 = new HashSet<IPPEA_DATA_ProductPackages>();
            this.IPPEA_DATA_ProductParts = new HashSet<IPPEA_DATA_ProductParts>();
            this.IPPEA_DATA_ProductParts1 = new HashSet<IPPEA_DATA_ProductParts>();
            this.IPPEA_DATA_ProductReplacements = new HashSet<IPPEA_DATA_ProductReplacements>();
            this.IPPEA_DATA_ProductReplacements1 = new HashSet<IPPEA_DATA_ProductReplacements>();
            this.IPPEA_DATA_ProductReviewRelation = new HashSet<IPPEA_DATA_ProductReviewRelation>();
            this.IPPEA_DATA_ProductShipMethods = new HashSet<IPPEA_DATA_ProductShipMethods>();
            this.IPPEA_DATA_ProductSocialMediaSubmission = new HashSet<IPPEA_DATA_ProductSocialMediaSubmission>();
            this.IPPEA_DATA_ProductSpecifications = new HashSet<IPPEA_DATA_ProductSpecifications>();
            this.IPPEA_DATA_ProductType = new HashSet<IPPEA_DATA_ProductType>();
            this.IPPEA_DATA_PromoProducts = new HashSet<IPPEA_DATA_PromoProducts>();
            this.IPPEA_DATA_PromotionProductReplacements = new HashSet<IPPEA_DATA_PromotionProductReplacements>();
            this.IPPEA_DATA_PromotionsLinks = new HashSet<IPPEA_DATA_PromotionsLinks>();
            this.IPPEA_DATA_QandAProductOptOut = new HashSet<IPPEA_DATA_QandAProductOptOut>();
            this.IPPEA_DATA_QandAProducts = new HashSet<IPPEA_DATA_QandAProducts>();
            this.IPPEA_DATA_QandAQuestion = new HashSet<IPPEA_DATA_QandAQuestion>();
            this.IPPEA_DATA_QuestionProduct = new HashSet<IPPEA_DATA_QuestionProduct>();
            this.IPPEA_DATA_QuoteItems = new HashSet<IPPEA_DATA_QuoteItems>();
            this.IPPEA_DATA_Recommendations = new HashSet<IPPEA_DATA_Recommendations>();
            this.IPPEA_DATA_Recommendations1 = new HashSet<IPPEA_DATA_Recommendations>();
            this.IPPEA_DATA_ShoppingCartItem = new HashSet<IPPEA_DATA_ShoppingCartItem>();
            this.IPPEA_DATA_TrackActivity = new HashSet<IPPEA_DATA_TrackActivity>();
            this.IPPEA_DATA_VendorBidServiceRelation = new HashSet<IPPEA_DATA_VendorBidServiceRelation>();
            this.IPPEA_DATA_VendorPriceRequest = new HashSet<IPPEA_DATA_VendorPriceRequest>();
            this.IPPEA_DATA_VendorProducts = new HashSet<IPPEA_DATA_VendorProducts>();
            this.IPPEA_DATA_WmsJobLog = new HashSet<IPPEA_DATA_WmsJobLog>();
            this.IPPEA_DATA_WmsJobs = new HashSet<IPPEA_DATA_WmsJobs>();
            this.IPPEA_DATA_WmsOrderProduct = new HashSet<IPPEA_DATA_WmsOrderProduct>();
        }
    
        public int ID { get; set; }
        public int ManufacturerID { get; set; }
        public string ProductCode { get; set; }
        public string Name { get; set; }
        public string ShortDescription { get; set; }
        public string LongDescription { get; set; }
        public string ProductPage { get; set; }
        public decimal Weight { get; set; }
        public Nullable<decimal> Height { get; set; }
        public Nullable<decimal> Length { get; set; }
        public Nullable<decimal> Width { get; set; }
        public string SmallImageName { get; set; }
        public string LargeImageName { get; set; }
        public bool IsActive { get; set; }
        public string ManufacturerCode { get; set; }
        public decimal Price { get; set; }
        public Nullable<decimal> SalePrice { get; set; }
        public bool IsShippable { get; set; }
        public Nullable<decimal> ShipPrice { get; set; }
        public string ProductNotes { get; set; }
        public string Warranty { get; set; }
        public string MetaDescription { get; set; }
        public string MetaKeyWords { get; set; }
        public bool IsPackage { get; set; }
        public bool IsPart { get; set; }
        public bool FreeShipping { get; set; }
        public System.DateTime DateAdded { get; set; }
        public bool ProductAvailability { get; set; }
        public Nullable<int> AvailabilityStatus { get; set; }
        public string AvailabilityNotes { get; set; }
        public bool NoShipIntl { get; set; }
        public bool ShipsAlone { get; set; }
        public bool IsEbayItem { get; set; }
        public bool IseBayItemUpdated { get; set; }
        public Nullable<int> StoreCategoryID { get; set; }
        public bool IsShoppingComItem { get; set; }
        public Nullable<int> ShoppingComCategoryID { get; set; }
        public bool IsNexTagItem { get; set; }
        public Nullable<int> NexTagCategoryID { get; set; }
        public bool IsShopzillaItem { get; set; }
        public Nullable<int> ShopzillaCategoryID { get; set; }
        public bool IsYahooShoppingItem { get; set; }
        public Nullable<int> YahooShoppingCategoryID { get; set; }
        public bool IsFroogleItem { get; set; }
        public Nullable<int> FroogleCategoryID { get; set; }
        public bool IsINYOPool { get; set; }
        public bool IsINYOWinter { get; set; }
        public bool IsFreightQuote { get; set; }
        public bool InXML { get; set; }
        public string PublicManufacturerCode { get; set; }
        public string Dimensions { get; set; }
        public bool NonBiddable { get; set; }
        public Nullable<int> FreightClass { get; set; }
        public bool CheckInActiveForInStock { get; set; }
        public bool NoDisplayPopularItems { get; set; }
        public string AltImage1 { get; set; }
        public string AltImage2 { get; set; }
        public string AltImage3 { get; set; }
        public string AltImage4 { get; set; }
        public string AltImage5 { get; set; }
        public string AltImage6 { get; set; }
        public bool ExpeditedShippingNotAvailable { get; set; }
        public bool NonReturnable { get; set; }
        public bool BypassLowMargin { get; set; }
        public bool IsBingShoppingItem { get; set; }
        public Nullable<int> BingShoppingCategoryID { get; set; }
        public string LongDescriptionOld { get; set; }
        public bool LongDescriptionCleaned { get; set; }
        public Nullable<int> ProductGroupID { get; set; }
        public Nullable<int> ProductGroupOrder { get; set; }
        public Nullable<decimal> RegularPrice { get; set; }
        public Nullable<decimal> RebateValue { get; set; }
        public Nullable<int> RebateMethodID { get; set; }
        public Nullable<int> ProductAttributeID { get; set; }
        public string OldAlternatePartNumbers { get; set; }
        public bool UnCheckIsActiveForNotInStock { get; set; }
        public string GTIN { get; set; }
        public Nullable<int> BackorderTypeID { get; set; }
        public Nullable<System.DateTime> BackorderDate { get; set; }
        public bool IncludeInactiveProductOnProductListing { get; set; }
        public bool SendProductAvailabilityEmail { get; set; }
        public Nullable<System.DateTimeOffset> DiscontinuedDate { get; set; }
        public Nullable<int> DiscontinuedReasonId { get; set; }
        public string HighRiskForFraudBy { get; set; }
        public Nullable<System.DateTimeOffset> HighRiskForFraudDate { get; set; }
        public string MarketingCategory { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IPPEA_DATA_CheckoutItem> IPPEA_DATA_CheckoutItem { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IPPEA_DATA_CheckoutItemProduct> IPPEA_DATA_CheckoutItemProduct { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IPPEA_DATA_ConversationProductMentions> IPPEA_DATA_ConversationProductMentions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IPPEA_DATA_CouponProducts> IPPEA_DATA_CouponProducts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IPPEA_DATA_DoItYourselfStory> IPPEA_DATA_DoItYourselfStory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IPPEA_DATA_DoItYourselfStoryProducts> IPPEA_DATA_DoItYourselfStoryProducts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IPPEA_DATA_eBayListings> IPPEA_DATA_eBayListings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IPPEA_DATA_eBayLogs> IPPEA_DATA_eBayLogs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IPPEA_DATA_HowToPageProductRelation> IPPEA_DATA_HowToPageProductRelation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IPPEA_DATA_ManualProduct> IPPEA_DATA_ManualProduct { get; set; }
        public virtual IPPEA_DATA_Manufacturer IPPEA_DATA_Manufacturer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IPPEA_DATA_MergeProduct> IPPEA_DATA_MergeProduct { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IPPEA_DATA_MergeProductLog> IPPEA_DATA_MergeProductLog { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IPPEA_DATA_OrderFormLineItem> IPPEA_DATA_OrderFormLineItem { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IPPEA_DATA_PartChartRows> IPPEA_DATA_PartChartRows { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IPPEA_DATA_PartProducts> IPPEA_DATA_PartProducts { get; set; }
        public virtual IPPEA_DECODE_ProductAvailability IPPEA_DECODE_ProductAvailability { get; set; }
        public virtual IPPEA_DECODE_BackorderType IPPEA_DECODE_BackorderType { get; set; }
        public virtual IPPEA_DECODE_BingShoppingCategories IPPEA_DECODE_BingShoppingCategories { get; set; }
        public virtual IPPEA_DECODE_ProductDiscontinuedReason IPPEA_DECODE_ProductDiscontinuedReason { get; set; }
        public virtual IPPEA_DECODE_FroogleCategories IPPEA_DECODE_FroogleCategories { get; set; }
        public virtual IPPEA_DECODE_NexTagCategories IPPEA_DECODE_NexTagCategories { get; set; }
        public virtual IPPEA_DATA_ProductAttribute IPPEA_DATA_ProductAttribute { get; set; }
        public virtual IPPEA_DATA_ProductGroup IPPEA_DATA_ProductGroup { get; set; }
        public virtual IPPEA_DECODE_RebateMethod IPPEA_DECODE_RebateMethod { get; set; }
        public virtual IPPEA_DECODE_ShoppingComCategories IPPEA_DECODE_ShoppingComCategories { get; set; }
        public virtual IPPEA_DECODE_ShopzillaCategories IPPEA_DECODE_ShopzillaCategories { get; set; }
        public virtual IPPEA_DECODE_StoreCategories IPPEA_DECODE_StoreCategories { get; set; }
        public virtual IPPEA_DECODE_YahooShoppingCategories IPPEA_DECODE_YahooShoppingCategories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IPPEA_DATA_ProductAccessories> IPPEA_DATA_ProductAccessories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IPPEA_DATA_ProductAccessories> IPPEA_DATA_ProductAccessories1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IPPEA_DATA_ProductAlternatePartNumbers> IPPEA_DATA_ProductAlternatePartNumbers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IPPEA_DATA_ProductAttributeProducts> IPPEA_DATA_ProductAttributeProducts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IPPEA_DATA_ProductAvailability> IPPEA_DATA_ProductAvailability { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IPPEA_DATA_ProductFeedGoogle> IPPEA_DATA_ProductFeedGoogle { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IPPEA_DATA_ProductMedia> IPPEA_DATA_ProductMedia { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IPPEA_DATA_ProductPackages> IPPEA_DATA_ProductPackages { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IPPEA_DATA_ProductPackages> IPPEA_DATA_ProductPackages1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IPPEA_DATA_ProductParts> IPPEA_DATA_ProductParts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IPPEA_DATA_ProductParts> IPPEA_DATA_ProductParts1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IPPEA_DATA_ProductReplacements> IPPEA_DATA_ProductReplacements { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IPPEA_DATA_ProductReplacements> IPPEA_DATA_ProductReplacements1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IPPEA_DATA_ProductReviewRelation> IPPEA_DATA_ProductReviewRelation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IPPEA_DATA_ProductShipMethods> IPPEA_DATA_ProductShipMethods { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IPPEA_DATA_ProductSocialMediaSubmission> IPPEA_DATA_ProductSocialMediaSubmission { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IPPEA_DATA_ProductSpecifications> IPPEA_DATA_ProductSpecifications { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IPPEA_DATA_ProductType> IPPEA_DATA_ProductType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IPPEA_DATA_PromoProducts> IPPEA_DATA_PromoProducts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IPPEA_DATA_PromotionProductReplacements> IPPEA_DATA_PromotionProductReplacements { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IPPEA_DATA_PromotionsLinks> IPPEA_DATA_PromotionsLinks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IPPEA_DATA_QandAProductOptOut> IPPEA_DATA_QandAProductOptOut { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IPPEA_DATA_QandAProducts> IPPEA_DATA_QandAProducts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IPPEA_DATA_QandAQuestion> IPPEA_DATA_QandAQuestion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IPPEA_DATA_QuestionProduct> IPPEA_DATA_QuestionProduct { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IPPEA_DATA_QuoteItems> IPPEA_DATA_QuoteItems { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IPPEA_DATA_Recommendations> IPPEA_DATA_Recommendations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IPPEA_DATA_Recommendations> IPPEA_DATA_Recommendations1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IPPEA_DATA_ShoppingCartItem> IPPEA_DATA_ShoppingCartItem { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IPPEA_DATA_TrackActivity> IPPEA_DATA_TrackActivity { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IPPEA_DATA_VendorBidServiceRelation> IPPEA_DATA_VendorBidServiceRelation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IPPEA_DATA_VendorPriceRequest> IPPEA_DATA_VendorPriceRequest { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IPPEA_DATA_VendorProducts> IPPEA_DATA_VendorProducts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IPPEA_DATA_WmsJobLog> IPPEA_DATA_WmsJobLog { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IPPEA_DATA_WmsJobs> IPPEA_DATA_WmsJobs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IPPEA_DATA_WmsOrderProduct> IPPEA_DATA_WmsOrderProduct { get; set; }
    }
}
