//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IPPEA.EntityData
{
    using System;
    using System.Collections.Generic;
    
    public partial class IPPEA_DATA_VendorPriceRequest
    {
        public int ID { get; set; }
        public int ProductID { get; set; }
        public int VendorID { get; set; }
        public Nullable<bool> AddProduct { get; set; }
        public Nullable<decimal> UnitPrice { get; set; }
        public string ManufacturerCode { get; set; }
        public Nullable<int> ShipMethodID { get; set; }
        public Nullable<int> InStock { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public int Approval { get; set; }
        public string Comment { get; set; }
    
        public virtual IPPEA_DATA_Product IPPEA_DATA_Product { get; set; }
        public virtual IPPEA_DATA_Vendor IPPEA_DATA_Vendor { get; set; }
    }
}
