//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IPPEA.EntityData
{
    using System;
    using System.Collections.Generic;
    
    public partial class IPPEA_DECODE_FraudReason
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public IPPEA_DECODE_FraudReason()
        {
            this.IPPEA_DATA_OrderGroup = new HashSet<IPPEA_DATA_OrderGroup>();
        }
    
        public int Id { get; set; }
        public string Reason { get; set; }
        public string Code { get; set; }
        public string Description { get; set; }
        public Nullable<int> FraudStatusId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IPPEA_DATA_OrderGroup> IPPEA_DATA_OrderGroup { get; set; }
        public virtual IPPEA_DECODE_FraudStatus IPPEA_DECODE_FraudStatus { get; set; }
    }
}
