//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IPPEA.EntityData
{
    using System;
    using System.Collections.Generic;
    
    public partial class IPPEA_DATA_HowToPage
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public IPPEA_DATA_HowToPage()
        {
            this.IP_DATA_HowToPageComments = new HashSet<IP_DATA_HowToPageComments>();
            this.IP_DATA_HowToPageRatingRelation = new HashSet<IP_DATA_HowToPageRatingRelation>();
            this.IPPEA_DATA_HowToInformation = new HashSet<IPPEA_DATA_HowToInformation>();
            this.IPPEA_DATA_HowToPageMedia = new HashSet<IPPEA_DATA_HowToPageMedia>();
            this.IPPEA_DATA_HowToPageProductRelation = new HashSet<IPPEA_DATA_HowToPageProductRelation>();
        }
    
        public int ID { get; set; }
        public string Title { get; set; }
        public string PageTitle { get; set; }
        public Nullable<int> ArticleCategoryID { get; set; }
        public string Keywords { get; set; }
        public string ImageFileName { get; set; }
        public Nullable<int> DifficultyID { get; set; }
        public string Description { get; set; }
        public bool IsDeleted { get; set; }
        public decimal AvgRating { get; set; }
        public int CountNum { get; set; }
        public string UserName { get; set; }
        public string AltImageText { get; set; }
        public Nullable<bool> InXml { get; set; }
        public bool IsActive { get; set; }
        public string VideoEmbedUrl { get; set; }
        public string PageDescription { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IP_DATA_HowToPageComments> IP_DATA_HowToPageComments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IP_DATA_HowToPageRatingRelation> IP_DATA_HowToPageRatingRelation { get; set; }
        public virtual IPPEA_DATA_ArticleCategory IPPEA_DATA_ArticleCategory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IPPEA_DATA_HowToInformation> IPPEA_DATA_HowToInformation { get; set; }
        public virtual IPPEA_DECODE_HowToDifficulty IPPEA_DECODE_HowToDifficulty { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IPPEA_DATA_HowToPageMedia> IPPEA_DATA_HowToPageMedia { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IPPEA_DATA_HowToPageProductRelation> IPPEA_DATA_HowToPageProductRelation { get; set; }
    }
}
