//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IPPEA.EntityData
{
    using System;
    using System.Collections.Generic;
    
    public partial class IPPEA_DATA_AuthNetSettings
    {
        public int ID { get; set; }
        public string Description { get; set; }
        public string AuthNetLogin { get; set; }
        public string AuthNetTranKey { get; set; }
        public Nullable<bool> EnablePreAuth { get; set; }
        public Nullable<bool> TestMode { get; set; }
        public Nullable<bool> Selected { get; set; }
        public Nullable<System.DateTime> VoidCutOffTime { get; set; }
    }
}
