//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IPPEA.EntityData
{
    using System;
    using System.Collections.Generic;
    
    public partial class IPPEA_DECODE_CarrierServiceCode
    {
        public int ID { get; set; }
        public string CarrierServiceCode { get; set; }
        public string CarrierServiceName { get; set; }
        public Nullable<int> CarrierID { get; set; }
        public Nullable<int> OLEACarrierShipMethod { get; set; }
        public Nullable<int> CheckSaturday { get; set; }
        public Nullable<int> CheckState { get; set; }
        public Nullable<int> CheckCanada { get; set; }
        public Nullable<bool> IsInternational { get; set; }
    }
}
