//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IPPEA.EntityData
{
    using System;
    using System.Collections.Generic;
    
    public partial class IPPEA_DATA_PartCategory
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public IPPEA_DATA_PartCategory()
        {
            this.IPPEA_DATA_PartCategory1 = new HashSet<IPPEA_DATA_PartCategory>();
            this.IPPEA_DATA_PartCategoryMedia = new HashSet<IPPEA_DATA_PartCategoryMedia>();
            this.IPPEA_DATA_PartPageCategories = new HashSet<IPPEA_DATA_PartPageCategories>();
            this.IPPEA_DATA_ProductCategory = new HashSet<IPPEA_DATA_ProductCategory>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public Nullable<int> ParentID { get; set; }
        public int ParentLevel { get; set; }
        public string Description { get; set; }
        public string CategoryPage { get; set; }
        public bool IsActive { get; set; }
        public int SectionID { get; set; }
        public string ImageName { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IPPEA_DATA_PartCategory> IPPEA_DATA_PartCategory1 { get; set; }
        public virtual IPPEA_DATA_PartCategory IPPEA_DATA_PartCategory2 { get; set; }
        public virtual IPPEA_DECODE_PartSectionTypes IPPEA_DECODE_PartSectionTypes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IPPEA_DATA_PartCategoryMedia> IPPEA_DATA_PartCategoryMedia { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IPPEA_DATA_PartPageCategories> IPPEA_DATA_PartPageCategories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IPPEA_DATA_ProductCategory> IPPEA_DATA_ProductCategory { get; set; }
    }
}
