//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IPPEA.EntityData
{
    using System;
    using System.Collections.Generic;
    
    public partial class IPPEA_DATA_PayPalTransLog
    {
        public int ID { get; set; }
        public System.DateTime TranDate { get; set; }
        public string TransactionID { get; set; }
        public int CustomerID { get; set; }
        public decimal Amount { get; set; }
        public string PayerEmail { get; set; }
        public System.DateTime PaymentDate { get; set; }
        public string PaymentStatus { get; set; }
        public string PendingReason { get; set; }
        public string PaymentType { get; set; }
        public string UserID { get; set; }
    
        public virtual IPPEA_DATA_Customer IPPEA_DATA_Customer { get; set; }
    }
}
