//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IPPEA.EntityData
{
    using System;
    using System.Collections.Generic;
    
    public partial class IPPEA_DATA_WmsShipments
    {
        public int Id { get; set; }
        public int OrderAssignmentId { get; set; }
        public int ShipmentId { get; set; }
        public string TrackingNumber { get; set; }
        public System.DateTimeOffset ShipmentDate { get; set; }
    
        public virtual IPPEA_DATA_OrderAssignment IPPEA_DATA_OrderAssignment { get; set; }
    }
}
