//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IPPEA.EntityData
{
    using System;
    using System.Collections.Generic;
    
    public partial class IPPEA_DATA_Quotes_Archive
    {
        public int ArchiveID { get; set; }
        public string ArchiveType { get; set; }
        public string ArchiveReason { get; set; }
        public int ArchiveUserID { get; set; }
        public System.DateTimeOffset ArchiveDt { get; set; }
        public int ID { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<int> CustomerID { get; set; }
        public Nullable<int> ServiceRepID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Company { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Zip { get; set; }
        public string Country { get; set; }
        public string Phone { get; set; }
        public string Fax { get; set; }
        public string Email { get; set; }
        public Nullable<System.DateTime> EmailSent { get; set; }
        public Nullable<int> StatusID { get; set; }
        public decimal SubTotal { get; set; }
        public decimal TaxRate { get; set; }
        public decimal Tax { get; set; }
        public decimal Shipping { get; set; }
        public decimal Handling { get; set; }
        public decimal Total { get; set; }
        public bool CustomShipping { get; set; }
        public bool UseTaxCertificate { get; set; }
        public bool ConvertedToOrder { get; set; }
        public Nullable<System.DateTime> DateConverted { get; set; }
        public bool IsDeleted { get; set; }
        public bool EmailReminder { get; set; }
        public int QuoteType { get; set; }
        public Nullable<int> ShipMethodID { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<int> OrderGroupId { get; set; }
        public Nullable<int> SupportTicketId { get; set; }
        public Nullable<int> QuestionId { get; set; }
        public bool PrefillCart { get; set; }
        public Nullable<int> SourceId { get; set; }
        public string SourceUri { get; set; }
        public bool AutoCreated { get; set; }
    
        public virtual IPPEA_DATA_Employees IPPEA_DATA_Employees { get; set; }
    }
}
