//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IPPEA.EntityData
{
    using System;
    using System.Collections.Generic;
    
    public partial class IPPEA_DATA_OrderAssignment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public IPPEA_DATA_OrderAssignment()
        {
            this.IPPEA_DATA_WmsOrderProduct = new HashSet<IPPEA_DATA_WmsOrderProduct>();
            this.IPPEA_DATA_WmsShipments = new HashSet<IPPEA_DATA_WmsShipments>();
        }
    
        public int ID { get; set; }
        public Nullable<int> AssignedToEmployeeId { get; set; }
        public string OrderID { get; set; }
        public System.DateTimeOffset CreateDate { get; set; }
        public Nullable<System.DateTimeOffset> CompletedDate { get; set; }
        public int OrderFormID { get; set; }
        public Nullable<int> CreatedByEmployeeId { get; set; }
        public Nullable<int> ShippingOrderId { get; set; }
        public Nullable<int> ShipmentId { get; set; }
        public Nullable<System.DateTimeOffset> ShippingOrderDate { get; set; }
        public Nullable<System.DateTimeOffset> ShipmentDate { get; set; }
        public Nullable<System.DateTimeOffset> PackListPrintDate { get; set; }
    
        public virtual IPPEA_DATA_Employees IPPEA_DATA_Employees { get; set; }
        public virtual IPPEA_DATA_Employees IPPEA_DATA_Employees1 { get; set; }
        public virtual IPPEA_DATA_OrderFormHeader IPPEA_DATA_OrderFormHeader { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IPPEA_DATA_WmsOrderProduct> IPPEA_DATA_WmsOrderProduct { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IPPEA_DATA_WmsShipments> IPPEA_DATA_WmsShipments { get; set; }
    }
}
