//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IPPEA.EntityData
{
    using System;
    using System.Collections.Generic;
    
    public partial class IPPEA_DATA_SupportEmails
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public IPPEA_DATA_SupportEmails()
        {
            this.IPPEA_DATA_SupportAttachmentMedia = new HashSet<IPPEA_DATA_SupportAttachmentMedia>();
            this.IPPEA_DATA_VendorSupportReplies = new HashSet<IPPEA_DATA_VendorSupportReplies>();
        }
    
        public int ID { get; set; }
        public Nullable<int> TicketID { get; set; }
        public string EmailFrom { get; set; }
        public string EmailTo { get; set; }
        public string EmailBcc { get; set; }
        public string EmailSubject { get; set; }
        public string EmailBody { get; set; }
        public Nullable<int> ServiceRepID { get; set; }
        public string UserID { get; set; }
        public Nullable<System.DateTime> DateEntered { get; set; }
        public Nullable<int> VendorRequestID { get; set; }
        public Nullable<int> EmailType { get; set; }
        public bool Reviewemail { get; set; }
        public string MessageID { get; set; }
        public Nullable<int> ProofStatus { get; set; }
        public bool HasStrippedBody { get; set; }
    
        public virtual IPPEA_DATA_Employees IPPEA_DATA_Employees { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IPPEA_DATA_SupportAttachmentMedia> IPPEA_DATA_SupportAttachmentMedia { get; set; }
        public virtual IPPEA_DECODE_SupportEmailTypes IPPEA_DECODE_SupportEmailTypes { get; set; }
        public virtual IPPEA_DATA_SupportTickets IPPEA_DATA_SupportTickets { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IPPEA_DATA_VendorSupportReplies> IPPEA_DATA_VendorSupportReplies { get; set; }
    }
}
