//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IPPEA.EntityData
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderAddress
    {
        public int uid { get; set; }
        public Nullable<int> OrderID { get; set; }
        public Nullable<int> Type { get; set; }
        public string FirstName { get; set; }
        public string MI { get; set; }
        public string LastName { get; set; }
        public string Company { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Zip { get; set; }
        public string Country { get; set; }
        public string Phone { get; set; }
        public string Fax { get; set; }
        public string EMail { get; set; }
        public string ShipMethod { get; set; }
        public string SpecialInstruction { get; set; }
        public string CountryTaxRate { get; set; }
        public string StateTaxRate { get; set; }
        public string LocalTaxRate { get; set; }
        public string DiscountTotal { get; set; }
        public Nullable<int> IsShippingTaxed { get; set; }
        public string ShippableShippingTotal { get; set; }
        public string HandlingTotal { get; set; }
        public Nullable<int> ShipType { get; set; }
        public string BackOrderShippingTotal { get; set; }
        public Nullable<int> BOQuantity { get; set; }
        public string NickName { get; set; }
        public Nullable<int> BOPending { get; set; }
        public Nullable<int> Pending { get; set; }
        public string ShipCarrierCode { get; set; }
        public string TotalBilled { get; set; }
        public string AmountRemaining { get; set; }
        public string CODAmount { get; set; }
    }
}
