//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IPPEA.EntityData
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderItem
    {
        public int uid { get; set; }
        public Nullable<int> OrderID { get; set; }
        public Nullable<int> ProductID { get; set; }
        public Nullable<int> AddressID { get; set; }
        public Nullable<int> Quantity { get; set; }
        public string ProductName { get; set; }
        public Nullable<int> IsOnSale { get; set; }
        public string Price { get; set; }
        public string SalePrice { get; set; }
        public Nullable<int> IsGiftWrap { get; set; }
        public string GiftwrapPrice { get; set; }
        public Nullable<int> GiftWrapQuantity { get; set; }
        public string ProductCode { get; set; }
        public Nullable<int> IsShipable { get; set; }
        public string ShipPrice { get; set; }
        public string Cost { get; set; }
        public Nullable<int> HasCountryTax { get; set; }
        public Nullable<int> HasStateTax { get; set; }
        public Nullable<int> HasLocalTax { get; set; }
        public string FileName { get; set; }
        public Nullable<int> Downloaded { get; set; }
        public string ItemPrice { get; set; }
        public Nullable<int> BackOrderedQty { get; set; }
        public string Category { get; set; }
        public string itemTotal { get; set; }
        public string VendorName { get; set; }
        public string Weight { get; set; }
        public string VendorEmail { get; set; }
        public Nullable<int> DownloadOneTime { get; set; }
        public string DownloadExpire { get; set; }
        public bool IsItemEbay { get; set; }
    }
}
