//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IPPEA.EntityData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Portal
    {
        public int ID { get; set; }
        public int PortalID { get; set; }
        public string PortalAlias { get; set; }
        public string PortalName { get; set; }
        public string PortalStyleSheet { get; set; }
        public string PortalDescription { get; set; }
        public string PortalHomeLink { get; set; }
        public string PortalKeyWords { get; set; }
        public string PortalWebTitle { get; set; }
        public bool AlwaysShowEditButton { get; set; }
    }
}
