//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IPPEA.EntityData
{
    using System;
    using System.Collections.Generic;
    
    public partial class PriceUpdateGps20110526
    {
        public int ID { get; set; }
        public string Item_ID { get; set; }
        public string Manufacturer__ { get; set; }
        public string Vendor { get; set; }
        public Nullable<double> Price { get; set; }
        public string F5 { get; set; }
    }
}
