//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IPPEA.EntityData
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProcessorResponse
    {
        public int uid { get; set; }
        public Nullable<decimal> OrderID { get; set; }
        public string CustTransNo { get; set; }
        public string MerchantTransNo { get; set; }
        public string AVSResult { get; set; }
        public string ActionCode { get; set; }
        public string RetrievalCode { get; set; }
        public string AuthorizationNo { get; set; }
        public Nullable<int> Success { get; set; }
        public string CVVResult { get; set; }
        public string ErrorLocation { get; set; }
        public string AuxMessage { get; set; }
        public string ErrorMessage { get; set; }
        public string FullResponse { get; set; }
    }
}
