//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IPPEA.EntityData
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductDetail
    {
        public int uid { get; set; }
        public Nullable<int> Type { get; set; }
        public Nullable<int> DisplayImage { get; set; }
        public Nullable<int> DisplayProductCode { get; set; }
        public Nullable<int> DisplayProductName { get; set; }
        public Nullable<int> DisplayCategory { get; set; }
        public Nullable<int> DisplayPriceSalePrice { get; set; }
        public Nullable<int> DisplayShortDescription { get; set; }
        public Nullable<int> DisplayLongDescription { get; set; }
        public Nullable<int> DisplayVendor { get; set; }
        public Nullable<int> DisplayManufacturer { get; set; }
        public Nullable<int> DisplayVolumePricing { get; set; }
        public Nullable<int> DisplayStockInfo { get; set; }
        public Nullable<int> DisplaySavedCartWishList { get; set; }
        public Nullable<int> DisplayEMailFriend { get; set; }
        public Nullable<int> DisplayLabels { get; set; }
        public Nullable<int> DisplayQty { get; set; }
        public Nullable<int> DisplayRecommendedProducts { get; set; }
        public Nullable<int> DisplayRecommendedImage { get; set; }
        public Nullable<int> DisplayRecommendedName { get; set; }
        public Nullable<int> DisplayRecommendedCode { get; set; }
        public Nullable<int> DisplayRecommendedShortDescription { get; set; }
        public Nullable<int> DisplayRecommendedPrice { get; set; }
        public Nullable<int> DefaultQty { get; set; }
        public Nullable<int> LinkImage { get; set; }
        public Nullable<int> LinkProductName { get; set; }
        public Nullable<int> LinkProductCode { get; set; }
        public string RecommendedTitle { get; set; }
        public Nullable<int> ImageSize { get; set; }
        public Nullable<int> IsActive { get; set; }
        public Nullable<int> DisplaySavings { get; set; }
        public Nullable<byte> AttributeDisplay { get; set; }
    }
}
