//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IPPEA.EntityData
{
    using System;
    using System.Collections.Generic;
    
    public partial class QBSetting
    {
        public int uid { get; set; }
        public Nullable<int> ToPrint { get; set; }
        public Nullable<int> OrderType { get; set; }
        public string Prefix { get; set; }
        public string LastNumber { get; set; }
        public string QBMemo { get; set; }
        public string ExtractedDate { get; set; }
    }
}
