//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IPPEA.EntityData
{
    using System;
    using System.Collections.Generic;
    
    public partial class QBTaxGroup
    {
        public int uid { get; set; }
        public string Sequence { get; set; }
        public string State { get; set; }
        public Nullable<int> Taxable { get; set; }
        public Nullable<int> IsGroupTax { get; set; }
        public string GroupName { get; set; }
        public string Rate { get; set; }
    }
}
