//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IPPEA.EntityData
{
    using System;
    using System.Collections.Generic;
    
    public partial class QBTemplate
    {
        public int uid { get; set; }
        public string PageName { get; set; }
        public string Sequence { get; set; }
        public string Description { get; set; }
        public Nullable<int> Active { get; set; }
        public Nullable<int> Skip { get; set; }
        public Nullable<int> ColumnVisible { get; set; }
    }
}
