//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IPPEA.EntityData
{
    using System;
    using System.Collections.Generic;
    
    public partial class SearchResult
    {
        public int uid { get; set; }
        public Nullable<int> Type { get; set; }
        public Nullable<int> DisplayImage { get; set; }
        public Nullable<int> DisplayProductCode { get; set; }
        public Nullable<int> DisplayProductName { get; set; }
        public Nullable<int> DisplayPriceSalePrice { get; set; }
        public Nullable<int> DisplayShortDescription { get; set; }
        public Nullable<int> DisplayVendor { get; set; }
        public Nullable<int> DisplayManufacturer { get; set; }
        public Nullable<int> DisplayVolumePricing { get; set; }
        public Nullable<int> DisplayStockInfo { get; set; }
        public Nullable<int> DisplayAddToCart { get; set; }
        public Nullable<int> DisplaySavedCartWishList { get; set; }
        public Nullable<int> DisplayEMailFriend { get; set; }
        public Nullable<int> DisplayMoreInfo { get; set; }
        public Nullable<int> DisplayLabels { get; set; }
        public Nullable<int> ProductsPerRow { get; set; }
        public Nullable<int> NumOfRows { get; set; }
        public Nullable<int> Alignment { get; set; }
        public Nullable<int> LinkImage { get; set; }
        public Nullable<int> LinkProductCode { get; set; }
        public Nullable<int> LinkProductName { get; set; }
        public Nullable<int> DefaultQty { get; set; }
        public Nullable<int> IsActive { get; set; }
        public Nullable<int> DisplayQty { get; set; }
        public Nullable<short> AttributeDisplay { get; set; }
    }
}
