//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IPPEA.EntityData
{
    using System;
    using System.Collections.Generic;
    
    public partial class SHIP_UPSNextDayAM
    {
        public Nullable<int> Weight { get; set; }
        public Nullable<decimal> Zone102 { get; set; }
        public Nullable<decimal> Zone103 { get; set; }
        public Nullable<decimal> Zone104 { get; set; }
        public Nullable<decimal> Zone105 { get; set; }
        public Nullable<decimal> Zone106 { get; set; }
        public Nullable<decimal> Zone107 { get; set; }
        public Nullable<decimal> Zone108 { get; set; }
        public Nullable<decimal> Zone124 { get; set; }
        public int ID { get; set; }
    }
}
