//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IPPEA.EntityData
{
    using System;
    using System.Collections.Generic;
    
    public partial class SHIP_UPSStandard
    {
        public Nullable<int> Weight { get; set; }
        public Nullable<decimal> Zone51 { get; set; }
        public Nullable<decimal> Zone52 { get; set; }
        public Nullable<decimal> Zone53 { get; set; }
        public Nullable<decimal> Zone54 { get; set; }
        public Nullable<decimal> Zone55 { get; set; }
        public Nullable<decimal> Zone56 { get; set; }
        public int ID { get; set; }
    }
}
