//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IPPEA.EntityData
{
    using System;
    using System.Collections.Generic;
    
    public partial class SHIP_UPSWorldwideSaver
    {
        public int ID { get; set; }
        public Nullable<int> Weight { get; set; }
        public Nullable<decimal> Zone481 { get; set; }
        public Nullable<decimal> Zone482 { get; set; }
        public Nullable<decimal> Zone484 { get; set; }
        public Nullable<decimal> Zone401 { get; set; }
        public Nullable<decimal> Zone402 { get; set; }
        public Nullable<decimal> Zone403 { get; set; }
        public Nullable<decimal> Zone404 { get; set; }
        public Nullable<decimal> Zone405 { get; set; }
        public Nullable<decimal> Zone406 { get; set; }
        public Nullable<decimal> Zone407 { get; set; }
        public Nullable<decimal> Zone408 { get; set; }
        public Nullable<decimal> Zone409 { get; set; }
        public Nullable<decimal> Zone412 { get; set; }
        public Nullable<decimal> Zone420 { get; set; }
        public Nullable<decimal> Zone421 { get; set; }
    }
}
