//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IPPEA.EntityData
{
    using System;
    using System.Collections.Generic;
    
    public partial class SHIP_UPS3Day
    {
        public int ID { get; set; }
        public Nullable<int> Weight { get; set; }
        public Nullable<decimal> Zone302 { get; set; }
        public Nullable<decimal> Zone303 { get; set; }
        public Nullable<decimal> Zone304 { get; set; }
        public Nullable<decimal> Zone305 { get; set; }
        public Nullable<decimal> Zone306 { get; set; }
        public Nullable<decimal> Zone307 { get; set; }
        public Nullable<decimal> Zone308 { get; set; }
    }
}
