//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IPPEA.EntityData
{
    using System;
    using System.Collections.Generic;
    
    public partial class SHIP_UPSWWZones
    {
        public int ID { get; set; }
        public Nullable<int> ZoneID { get; set; }
        public Nullable<int> CountryID { get; set; }
        public string CountryDescription { get; set; }
    }
}
