//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IPPEA.EntityData
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShoppingCartItem
    {
        public int uid { get; set; }
        public Nullable<int> CartID { get; set; }
        public Nullable<int> ProductID { get; set; }
        public Nullable<int> Quantity { get; set; }
        public string ReferalAddress { get; set; }
        public Nullable<int> GiftWrapQty { get; set; }
        public Nullable<bool> IsItemEbay { get; set; }
        public Nullable<decimal> EbayPrice { get; set; }
    }
}
