//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IPPEA.EntityData
{
    using System;
    using System.Collections.Generic;
    
    public partial class SSFroogleAdmin
    {
        public int uid { get; set; }
        public string Username { get; set; }
        public string FPassword { get; set; }
        public string FTPServer { get; set; }
        public Nullable<int> FTPConnectMode { get; set; }
        public string Filename { get; set; }
        public Nullable<int> ProductSelection { get; set; }
        public Nullable<int> Price { get; set; }
        public Nullable<int> DescSize { get; set; }
        public Nullable<int> ImageSize { get; set; }
        public Nullable<int> UpdateFrequency { get; set; }
        public Nullable<int> AutoFeed { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> LastDate { get; set; }
        public Nullable<int> Category { get; set; }
        public string QueryString { get; set; }
        public string ISBNFunction { get; set; }
        public string UnavailableImages { get; set; }
        public Nullable<int> IncludeBrand { get; set; }
        public Nullable<int> IncludeCurrency { get; set; }
        public Nullable<int> IncludeInstock { get; set; }
        public Nullable<int> IncludeIsbn { get; set; }
        public Nullable<int> IncludeShipping { get; set; }
    }
}
