//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IPPEA.EntityData
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int UserID { get; set; }
        public string UserName { get; set; }
        public string FullName { get; set; }
        public string Email { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<int> StatusID { get; set; }
        public string IsCustomer { get; set; }
        public string IsEmployee { get; set; }
        public Nullable<System.DateTime> LastLogin { get; set; }
        public Nullable<System.DateTime> LastActivity { get; set; }
        public string Location { get; set; }
        public byte[] Password { get; set; }
        public Nullable<System.DateTime> LastLogOffDt { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
    }
}
