//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IPPEA.EntityData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Walkin_Archive
    {
        public int uid { get; set; }
        public string SessionID { get; set; }
        public Nullable<int> CustomerID { get; set; }
        public Nullable<int> IsSignedIn { get; set; }
        public string CreatedDate { get; set; }
        public string OandaRate { get; set; }
        public string OandaISO { get; set; }
    }
}
